### ISSUE TITLE
Run code in the background on push notification

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#1002]
We need the ability to run code in the background (when the app is not running) on a push notification. We just need to be able to execute this callback in Flutter for now (not need to do it in YAML). 

There's is a already the hook in NotificationManager's `init(firebasePayload, backgroundNotificationHandler)`, but I couldn't get this handler to be called. The task is to successfully call this handler WHILE the app is in the background

**Comment by vinothvino42** [comment]
I tested it and working fine. We need to update the payload and also need to call this `backgroundMessageHandler` initially in the main method.

Payload:

```json
{
    "to": "token",
    "priority": "high",
    "content_available": true,
    "notification": {
      "title": "Ensemble",
      "body": "Ensemble App Developer"
    },
    "data" : {
        "foo": "EnsembleUI"
    }
}
```

**Comment by vinothvino42** [comment]
This is working fine now with the above payload. It's fixed
