### ISSUE TITLE
Ensemble Mono repo

### ISSUE THREAD

**Issue by snehmehta** [EnsembleUI/ensemble#1014]
We have a number of packages and growing. In order to properly maintain them, I suggest converting following packages multiple repo into single mono repo.

- https://github.com/EnsembleUI/ensemble_location
- https://github.com/EnsembleUI/ensemble_camera
- https://github.com/EnsembleUI/ensemble_module_auth
- https://github.com/EnsembleUI/ensemble_file_manager
- https://github.com/EnsembleUI/ensemble_notification
- https://github.com/EnsembleUI/ensemble_contacts

Reference: https://github.com/firebase/flutterfire

**Comment by kmahmood74** [comment]
I completely agree with this. There are too many repos everywhere. 

Also add https://github.com/snehmehta/table_calendar to it. That should be under EnsembleUI org and does not need to be a separate repo. Something like that can just be part of the core package

**Comment by snehmehta** [comment]
same as #865
