### ISSUE TITLE
keyboard doesn't close clicking inactive places

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1017]
see this here, if you click on note input, the keyboard will open up covering the whole input, and there is no way to get out of this keyboard, ideally if you click outside the input keyboard should close automatically

https://studio.ensembleui.com/app/YQGEapU8rrEfhTJJLzz8/screen/gBr5JHleY614Lw4xTGeG

**Comment by vinothvino42** [comment]
@sharjeelyunus PR - https://github.com/EnsembleUI/ensemble/pull/1020
