### ISSUE TITLE
keyboard done button with Multiline text input

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1018]
with Multiline text input keyboard shows the button to move to the next line, but for some places, we need the done button instead of the next line button, The done button is basically to close the keyboard

This is the next line button right now with a multiline keyboard
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/07532fb6-f75b-4a18-95e9-33742bab66eb)

Here is an example of a done button with a multiline keyboard
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/b33e379a-bead-410a-9b41-3e6eb684610a)

Discussion: https://discord.com/channels/1031982848485359626/1176573225157791784

**Comment by vinothvino42** [comment]
PR - 1021  & 1036
