### ISSUE TITLE
Need contact photo using getPhoneContacts action

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#1023]
## Introduction
Need ability to use contact `photo` when using `getPhoneContacts` action

## Details
Picture attached for one of the contact, console logged using `event.data['contacts']`
![image](https://github.com/EnsembleUI/ensemble/assets/32386713/679dac68-fe37-4ca5-9586-d4cf6a8045df)
![image](https://github.com/EnsembleUI/ensemble/assets/32386713/5eb5ce53-81c2-48d2-a239-f88ad97f8bb8)

## Note
Noticed another thing, `photo` is null for contact which has no picture.
For contact which has a picture, there's no `photo` key but `thumbnail` which is an integer array

**Comment by kmahmood74** [comment]
@vinothvino42 this has been in progress for 3 weeks! Please update, what's stopping you from finishing it? 
cc @snehmehta @vusters

**Comment by kmahmood74** [comment]
@vinothvino42 update please

**Comment by vinothvino42** [comment]
@kmahmood74 It's completed - https://github.com/EnsembleUI/ensemble/pull/1059

**Comment by anserwaseem** [comment]
@vinothvino42 
Reopening this issue, need following things:
1. Ability to use `getPhoneContactPhoto` action in js code
2. kitchen sink example (should work on our phone apps like Ensemble Go)
3. Schema update for studio

**Comment by vinothvino42** [comment]
Added the action to use it from the JS Code

PR - https://github.com/EnsembleUI/ensemble/pull/1187
Schema - https://github.com/EnsembleUI/ensemble-web-studio/pull/711
