### ISSUE TITLE
Lottie widget does not propagate click event

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#104]
When my Column includes a `onTap` action, I expect the entire Column to fire the action. But when the Column includes a Lottie, the Lottie area is not firing the action.

Example (line 42):
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/576f3004-83e6-429d-b256-628d85e05f7f

**Comment by kmahmood74** [comment]
checked in. you will need to specify onTap on Lottie itself too.
See https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/576f3004-83e6-429d-b256-628d85e05f7f
            - Lottie:
                source: https://assets8.lottiefiles.com/packages/lf20_m7yluel0.json
                styles:
                  width: 150
                  height: 150
                onTap:
                  action: showToast
                  options:
                    dismissable: true
                    type: success
                    message: Lottie click worked
                    duration: 3
