### ISSUE TITLE
When a push notification is received, the badge sets to 1 until the app is opened

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#1040]
When a push notification is received, the badge sets to 1 until the app is opened

https://github.com/EnsembleUI/ensemble/assets/32386713/d5b6bd6b-48a2-49cf-9f26-9f4b74cab01e

**Comment by vinothvino42** [comment]
@anserwaseem Are you doing the badge logic in the `backgroundNotificationHandler` method?

**Comment by vinothvino42** [comment]
@anserwaseem It's because the backend is sending the payload with a badge count of 1 always. I hope removing it will solve the problem.

**Comment by vusters** [comment]
Yes, this is not a problem. Backend sent the badge count - it should remove it.
