### ISSUE TITLE
Expose App information to be used inside the app

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#1041]
## Problem
i want to send following information to api
`appId` e.g. J4nZIEFlZTv2HQGwK15W (ensemble studio appId)
`appVersion` e.g. 1.2.3 (the version of app in App Store (or Testflight))

## UseCase:
Customer wants to post this information when "Rate Us" button is tapped and user is bounced to app store for rating

**Comment by kmahmood74** [comment]
@vinothvino42 this should be a quick one

**Comment by vinothvino42** [comment]
PR - #1122
