### ISSUE TITLE
Deep linking - User should be able to share link to any app within Ensemble Go/Preview.

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1046]
There are two types of links - (a) Link to an app/screen in the studio (b) Link to an app in preview
For this ticket, we are only talking about b i.e. links to preview an app. 

User A shares the Preview link to an app in email, sms etc. We do this today in our monthly updates. 
User B click on that link

Scenario #1 - User B is on a Laptop
 - App opens up in the browser in preview mode. 

Scenario #2 - User B is on a phone (iOS or Android) and does NOT have Ensemble Preview/go installed
- User is prompted to install Ensemble Preview or Go depending on the device
- User installs the app
- clicks on the link again and this time it goes to Scenario #3

Scenario #3 - User B is on a phone (iOS or Android) and has the Ensemble Go/Preview installed
- Ensemble Go/Preview opens up and takes the user to the right app

**Comment by kmahmood74** [comment]
cc @vusters @amin-nas please review the flow above. 
We'll need some enhancements to the editor as well but I'll create a separate ticket for that

**Comment by vinothvino42** [comment]
@kmahmood74 

**Scenario 1** - It works normally

**Scenario 2** - This can't be done easily in the native way (using Android App Links for Android or Universal Links for iOS). Simply it'll open the link to the browser, it'll not redirect to the app store (google play store or apple app store). This method is generally called Deferred Deep Links

There are two ways we can do it.
1. Using services like a branch or Firebase dynamic links (it's deprecated). In this way, it'll handle the redirection to the app store if the user has not installed the app on their device
2. Manual approach needs to configured in the web app to redirect to the app store - See the following links
Link 1: https://stackoverflow.com/a/54352873/4608334
Link 2: https://stackoverflow.com/a/41644344/4608334
Link 3: https://stackoverflow.com/a/45014683/4608334

**Scenario 3** - This can be done.

We already configured a few things for our ensemble (Android and iOS)
Android - https://ensembleui.com/.well-known/assetlinks.json
iOS - https://ensembleui.com/.well-known/apple-app-site-association

We must handle the redirection inside the link based on the URL parameters. 
For ex: www.studio.ensembleui.com/:appId/screens/:screenId

**Comment by kmahmood74** [comment]
Thanks @vinothvino42 Let's integrate https://www.branch.io/pricing/ It is free for 10K MAUs and fairly reasonable above that. No reason for us to build it ourselves. If we reach above 10K and start seeing high costs, we can always consider it then. Besides a customer needs integration with branch.io anyway

Create a ticket for the server work and assign to @tibrahulz

**Comment by vinothvino42** [comment]
It's done

**Comment by vinothvino42** [comment]
Need to integrate creating a branch link in the ensemble live app's share feature menu

**Comment by kmahmood74** [comment]
closing as done
