### ISSUE TITLE
Enhance Video Widget

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#1049]
Need to support this tutorial being played using Video widget _(required for a customer)_

https://github.com/EnsembleUI/ensemble/assets/32386713/e1efc8dc-9442-4b40-9ef0-8e103d25c4d7

Need following enhancements:
2. `PauseIntervals` property e.g., [3000, 5500, 7250]
3. `OnPause` action
4. `OnComplete` action
5. `enableLoop` prop (not required for my use case but nice to have)
6. `autoPlay` prop
7. `showControls` prop
8. `volume` prop

**Comment by vusters** [comment]
Remove ms -> seconds. I'll handle that separately across the entire system

**Comment by vinothvino42** [comment]
@vusters PR - #1062
