### ISSUE TITLE
Fix onTap of BottomNavBar item

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#1051]
Getting this error when using `onTap` action for BottomNavBar item
![image](https://github.com/EnsembleUI/ensemble/assets/32386713/59f1cc56-6f30-414d-94a8-5efab4fd2366)

**Comment by kmahmood74** [comment]
@anserwaseem Vu fixed it recently as part of another ticket. Please try again. closing it, re-open if it is still an issue
