### ISSUE TITLE
Migrating to flutter 3.16

### ISSUE THREAD

**Issue by snehmehta** [EnsembleUI/ensemble#1056]
- [x] Fix the deprecating issues with flutter_maps
- [x] Move our PR test to latest flutter version as well
- [x] Set latest to build as well

**Comment by kmahmood74** [comment]
is this done? @hemish11

**Comment by hemish11** [comment]
Yes @kmahmood74 it's done. The mono repo is also done with the same!

**Comment by kmahmood74** [comment]
closing as we have #1325 now
