### ISSUE TITLE
Sidebar footer does not work when used in ViewGroup

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1060]
Test app here:
https://studio.ensembleui.com/app/st8n8I4ss1a5uUAqpQq9/screens

**Comment by vusters** [comment]
@vinothvino42 please look into this regression. Footer used to work for sidebar. Also check the header.

**Comment by amin-nas** [comment]
@vinothvino42 @vusters we need this by Wednesday 27th so we can deliver the next KPN build.

**Comment by vinothvino42** [comment]
@vusters @amin-nas Created a PR - https://github.com/EnsembleUI/ensemble/pull/1094

**Comment by vinothvino42** [comment]
@amin-nas @vusters Fixed the API definition not found issue inside the sidebar's content page. Here's the PR - #1100
