### ISSUE TITLE
No GraphQL example in Kitchen Sink

### ISSUE THREAD

**Issue by RuthLHanan** [EnsembleUI/ensemble#1066]
I can't find any example of "graphQL APIs - how to call graphQL APIs with queries and handle graphQL responses" in kitchen sink, could someone create one?

**Comment by kmahmood74** [comment]
@sharjeelyunus I know you have worked with GraphQL, could you please create an example of that. It's de ja vu ;-)

**Comment by sharjeelyunus** [comment]
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/iolpq1iU1CnjPZuJeDd1
