### ISSUE TITLE
iOS Simulator: Exceptions and other issues on the chartjs page in Kitchen Sink (works fine on chrome)

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#107]
Open Kitchen sink in Ensemble Starter on iOS Simulator
Tap on ChartJs - https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/5d7b84de-3bbd-456e-aeea-98e2c9f4c3c7

<img width="337" alt="image" src="https://user-images.githubusercontent.com/10066434/202339538-0d13086e-2bb2-4d6f-8b75-b615e963c6d6.png">

on the console - 
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/10066434/202339696-b18c15d5-7fd9-4139-be8e-2f482764e116.png">

When I hit the back button to go back to the Kitchen Sink home, I get this exception - 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/10066434/202339788-68da393d-fd00-4253-93e4-1cc258ec7247.png">

**Comment by kmahmood74** [comment]
I probably had an issue in my code, this is ok now. Feel free to close @vusters

**Comment by vusters** [comment]
Yup. Confirmed working properly across devices. Closed.
