### ISSUE TITLE
Provide proper example for using default Camera and Gallery selection in Kitchen Sink 

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1077]
Default Camera is there but then there is no option to select from Gallery. How do I configure default behavior for Gallery. 

@sharjeelyunus you did this for myplace right?

**Comment by snehmehta** [comment]
it's actual in `pickFiles` action
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/fEYmyCSKcw6IODpgblKs
