### ISSUE TITLE
Menu: bottomNavBar throws error for Search

### ISSUE THREAD

**Issue by omermahmood** [EnsembleUI/ensemble#1079]
Page:
[Menu: bottomNavBar](https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/aa634599-cd5d-411c-a4b6-1163f3b5c558)

click on the middle yellow icon on the bottom navbar. It is supposed to navigate to the Lottie screen but errors out instead. 

```
      - icon: 
          name: note_add
        floating: true
        floatingAlignment: center
        floatingMargin: 5
        onTap: |
          //@code
          ensemble.navigateScreen('Lottie');
```

Error:
Error From INSIDE FRAME_WORK
main.dart.js:60034 ----------------------
main.dart.js:60034 Error :  Line: 3 in YAML and Line: 1 within the code block. Error Message: Error while executing method: ensemble.navigateScreen('Lottie'). Underlying error:Exception: Cannot find ScopeManager to execute action
main.dart.js:60034 StackTrace :  null

**Comment by kmahmood74** [comment]
@vusters another context regression. Please fix it quickly as it is a major blocker that impacts kitchen sink and probably many other apps in production

cc @snehmehta

**Comment by vusters** [comment]
fixed
