### ISSUE TITLE
Change Ensemble Live's home page to be an Ensemble App

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1083]
- have a public app in EDL with the home screen that will be presented to the user as the landing page of the Go/Preview apps
- When user selects an app from the list, enters appid or scans QR code (all within EDL), the EDL calls a event or method in Flutter code with the appid/screenid. Flutter code takes over and does what it does today i.e. navigates to that app.

**Comment by amin-nas** [comment]
@kmahmood74 thanks, please update!

**Comment by kmahmood74** [comment]
@amin-nas let me know when you have that front page app, I can do the flutter part

**Comment by kmahmood74** [comment]
@amin-nas let me know how to proceed on this, our Ensemble go and preview apps really look bad

**Comment by kmahmood74** [comment]
@vinothvino42 this is high priority. It's actually for Ensemble Live. 

1. Ensemble live should load the Ensemble app with id: 4qJvbIFIJ5Vou69P42l1
2. provide a flutter method that is passed into Ensemble and that Ensemble app is able to call when user scans a QR code of a an app. This flutter method will then take the user to the app s/he scanned

Let me know if you have questions

**Comment by vusters** [comment]
@amin-nas done and closing?
