### ISSUE TITLE
TextInput is not expandable /  shows a 4/5th of a line and then hides typing

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1097]
When typing a message to another user, I only get 3/4 of one line. The text box should expand so I can see more of what I am typing.

See this example
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/c9e4c772-6830-4f45-8382-b0a9fb0e75de)

Initial state
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/2dc58d99-fb02-45ba-8655-0dc46d0fd421)

**Comment by kmahmood74** [comment]
@hemish11 this is needed for a customer. please treat it as urgent
