### ISSUE TITLE
Toast message should wrap based on the screen width

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#1108]
Toast message should wrap and not be in a single line like the screenshot

![Image](https://github.com/EnsembleUI/ensemble/assets/622269/6e46e992-7391-45ca-8018-1d9a35093717)

**Comment by vinothvino42** [comment]
It's not working only when we set left and right for alignment toastGravity (ex: topRight, bottomLeft). I'm checking it

**Comment by vinothvino42** [comment]
PR - #1193
