### ISSUE TITLE
Switch | Intermediate State

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1154]
By default there should be only 2 states, but if user configures for 3, Switch should have 3 states, like below.

here we have data coming from the api, and we select 2 or more dates, if availablity is open then we keep it false, if its closed then true, and if its true and false at the same time on different select dates (mixed availability) then we want to show switch in between.

In between state should also have special styling properties like mentioned bellow

![Screenshot_2024-01-18-00-56-31-426-edit_com figma mirror](https://github.com/EnsembleUI/ensemble/assets/61178058/6db5f6db-cc71-4cbb-b026-335d4e7032a1)

**Comment by sharjeelyunus** [comment]
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/2a1403ec-7a0b-4e4c-9e21-9fae1c7e0617)

**Comment by sharjeelyunus** [comment]
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/b4fb4bda-a0a0-422a-9d63-49b1475a8115)

**Comment by vinothvino42** [comment]
PR - #1160
