### ISSUE TITLE
Notifications | Screen Name is compulsory???

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1166]
I'm getting this as notification payload

```
{
    “conversation_id”,
    “guest_id”,
    “host_id”,
    “property_id”,
    “property_city”,
    “notification_type”
}
```

and based on notification type I want to navigate the user to a screen. apparently, this isn't possible, it won't even accept the notification, in console I'm getting: `No screenId nor screenName provided on the notification. Ignoring...`

this shouldn't be the case, When I click on a notification, it should open the app and take me to the default "Home Screen", and from there I can navigate the user to whichever screen I want based on notification_type.

**Comment by vusters** [comment]
on notification, if screenId nor screenName is specified, takes the user to the home screen (don't just open the app) with the following payload:
```json
notificationPayload: {
  notification: {
    // .. notification block
  }
  data: {
    // .. data block
  }
  ..// other block
}
The home screen can access it by:
```
View:
  onLoad: |
    // has notification
    if (notificationPayload != null) {
      
    }
    ```

**Comment by vinothvino42** [comment]
@vusters Can you review it? Here's the PR - #1169

**Comment by vusters** [comment]
Fixed under https://github.com/EnsembleUI/ensemble/pull/1175.
@sharjeelyunus Please disregard the above. The notification payload will be:
```
notificationPayload: {
  title: "optional title",
  body: "optional body",
  data: {
    // data if sent by the server. Empty otherwise
  }
}
```
You can do this on the screen that handles notification:
```
View:
  onLoad: |
    if (notificationPayload != null) {
      // process notification
    } else {
        // regular page logic
    }
```
