### ISSUE TITLE
Ensemble.debug in browser

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#117]
`console.log('my debug message');` does not appear in browser's dev tool

**Comment by amin-nas** [comment]
@vusters I suggest supporting `console.log()` since that's what JS developers would expect.

**Comment by kmahmood74** [comment]
fixed - https://github.com/EnsembleUI/ensemble_ts_interpreter/commit/5ad299c6f9deb0fda1967011560a49378251fa5b

just do console.log('your log message') and it will appear on the console
