### ISSUE TITLE
Expose more info about the device

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1171]
As an app developer, I want to know what type of device is being used to render the app so that I can customize my UI.

As first step, research and propose available options. Few thoughs:

- `device.type` => smartphone, tablet, tv, desktop, ...
- `device.platform` => ios, android, android tv, web, ...
- `device.vendor` => apple, samsung, ...

**Comment by TheNoumanDev** [comment]
Example updated on Kitchen Sink: https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/X4CAuRtGsjBTMnACPhd7

Documentation added: https://docs.ensembleui.com/utilities/device
