### ISSUE TITLE
Enhance Carousal by exposing more configuration options

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1173]
Expose the following options for the Carousal widget, sample values below from the flutter package - 

      aspectRatio: 16/9,
      viewportFraction: 0.8,
      autoPlayAnimationDuration: Duration(milliseconds: 800),
      autoPlayCurve: Curves.fastOutSlowIn, //support most of the Curves
      enlargeCenterPage: true, 
      enlargeFactor: 0.3,
      onPageChanged: callbackFunction,
      scrollDirection: Axis.horizontal //or Axis.vertical

also the carousal widget today is slow as it doesn't use the builder pattern and tries to draw all the items at the same time instead of on-demand. 

Please add an option called - 
```
buildOnDemand: boolean
Default is false when item count <= 5
Default is true when item count >6
When true, use the itemBuilder pattern to draw widgets on demand
```

There is a lot there that we are not exposing. Also lots of room for performance improvement

**Comment by kmahmood74** [comment]
cc @vusters

**Comment by vinothvino42** [comment]
@snehmehta Can you check this PR - #1179
