### ISSUE TITLE
SignIn with Google not working on Android

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1177]
SignIn with Google is using Auth Module, It is working fine on the iOS / Ensemble Go app, but on Android, it isn't

Flow
- Show SignIn with Google button (working on both)
- onTap shows user's Google accounts (working on both)
- on selecting an account, sign in as the user and return idToken and auth data (not working on Android)

**Comment by kmahmood74** [comment]
@sharjeelyunus if this works now please close
