### ISSUE TITLE
Dropdown Bug

### ISSUE THREAD

**Issue by Ahsen6** [EnsembleUI/ensemble#1186]
Once an auto-complete's drop down's value is selected, it remains there even if i delete/remove the text. I encountered this issue while attempting to make a button enabled only if the user had selected a certain dropdown value, and disabled otherwise. But removing the value after initially selecting it doesn't disable the button. Works fine for a regular dropdown but not for dropdown with autoComplete set to true. 

Deleting the text that pertains to the dropdown value should delete the value. Here's the sample yaml:

``` 

- Dropdown:
      hintText: For e.g poster design
      id: autoComplete
      autoComplete: true
      items: ${getAllCategories()}
      label: Gig category
      styles:
         fillColor: transparent

**Comment by vinothvino42** [comment]
PR - https://github.com/EnsembleUI/ensemble/pull/1188
