### ISSUE TITLE
Blank definition should render a blank screen instead of error

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#1210]
A blank definition could be a valid start state, and so Runtime should render a blank screen instead of showing an error today.

![Image](https://github.com/EnsembleUI/ensemble/assets/622269/510cee56-3d3a-4274-83be-4a9c5bd36534)

**Comment by vinothvino42** [comment]
WIP PR - #1239

**Comment by vusters** [comment]
Completed
