### ISSUE TITLE
Android App does not support Html widget and menu

### ISSUE THREAD

**Issue by gaurikalp** [EnsembleUI/ensemble#122]
Unsupported widget error on android app screen, but displayed in ensemble studio
After removing the HTML widget from that screen, the Android app displays the screen correctly.
Also Menu display: drawer is not working on Android App.

![OnAndroidPhoneEligibility](https://user-images.githubusercontent.com/115991454/204760521-7e1ce562-9193-4652-afef-7ea31e2f12d6.jpeg)
![EnsembleStudioEligibility](https://user-images.githubusercontent.com/115991454/204760547-a6e7a3eb-6026-4e20-930f-f8b28d270710.PNG)

**Comment by vusters** [comment]
@gaurikalp looks like you are not on the latest Android version. Can you remove the current app, go here and re-install https://play.google.com/store/apps/details?id=com.ensemble.preview&hl=en-US&ah=aPo1RyffW5zntKBfhWWUv0ri_cA&pli=1

For drawer menu, make sure you have at least 1 menu item. Let me know if that doesn't work.

**Comment by gaurikalp** [comment]
Yes this problem fixed in updated version, Thank you.
