### ISSUE TITLE
Add readyOnly and selectable prop for free-form input field

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1220]
For these widgets, i want to be able to set readOnly and selectable:

1. TextInput
2. PasswordInput
3. Form

Acceptance criteria:
1. Default values are `readOnly: false` and `selectable: true`
2. When I only set `readOnly: true`, and do not set enabled or selectable props, user should be able to select the value and copy it. User should not be able to modify the value.
3. When I only set `enabled: fase`, widget should ignore the `readOnly` prop. The widget will not be clickable at all.
4. When I set `readOnly` at the parent Form widget, the value must cascade to children of the Form that are TextInputs and PasswordInputs.

**Comment by vinothvino42** [comment]
PR - #1234

**Comment by vusters** [comment]
completed.
