### ISSUE TITLE
Camera integration

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#128]
1. User can access the camera (photo/video) and device gallery via Ensemble Action (e.g. button click). 
Here's a sample action (also see showDialog action for implementation reference):
```yaml
Button:
  label: Open Camera
  onTap:
    action: openCamera
    options:
      useGallery: true              # see below for all options
    onComplete:
      //@code
      # access to the files here, which could be empty
```

2. When this action is taken, open this camera widget in full screen.
![Image](https://user-images.githubusercontent.com/622269/213077197-45053c10-6fa1-4e1f-b90f-b4c7a6145502.png)

3. Once the user have complete this Action (either take or pick a file or decide to cancel), the camera popup will close and invoke the Action callback onComplete, which will have reference to the files (if any).

These are all the options the user can pass in:
- mode: both (DEFAULT) | video | photo. Either allow taking video only OR taking photo only OR both. Only prompt for microphone access for "video" or "both" mode. If "both" mode is selected, default view to Video record.
- initialCamera: auto (DEFAULT to back camera) | front | back. If the preferred camera is not available, then use the other available one.
- useGallery: true (DEFAULT) | false. Show the button to pick images/videos from the photo gallery. Users should be prompted for file access permission ONLY when clicking on this button.
- maxCount: integer (DEFAULT 1). The max number of files allowed (either via camera or gallery).
- preview: true | false (DEFAULT).
     - If Preview is false: a) If maxCount is 1, close and immediately invoke the callback. b) if maxCount is > 1, show the Done button. Clicking on it will close and invoke the callback.
     - If Preview is true: follow the specs (Next button to go to next screens where they can remove/preview...)

These are not explicit options but implied automatically:
- Show camera flipping button if there are more than 1 camera available.

--------------------------------------------------------------------------
--------------------------------------------------------------------------
Outdated specs (for reference):

@hamxa152 There are two modes - 

1. Camera - this puts the camera either inline on the page or as full screen view (if configured)
2. ImagePicker - this puts a button on the page. When user clicks on the button, it launches either the camera or the photo picker depending on what's configured. 

**Camera** should have the following properties - 
All these properties are optional. 

- height
- width
- fullScreen: default: false. When specified, it ignores height and width and opens the camera full screen like tiktok
- video: default: true. When set to false, user should not be able to select an existing video or record a new one and can only deal with images
- selectMultiple:  default: true. When set to false, user should only be able to select one item (video or image is controller by the other option)
- select:  default: true. When false, do not allow selecting existing images/videos. 
- initialCamera: either front or back. Default is back. 
- allowFlippingCamera: if set to true, user should see the icon to flip the camera from front to back or vice versa. Default is true. 

**Image_Picker** should be able to launch the Camera or just the gallery

Please review these and let us know if any of these is not supported in Flutter package. We can skip those for now that are not supported. 

@vusters please review

**Comment by kmahmood74** [comment]
this is the same as #131

**Comment by kmahmood74** [comment]
@JasPanesar are you suggesting capturing video from both front and back cameras at the same time? I know some phones have that capability but not sure if it is yet supported in a flutter package. do you know of a flutter package that supports it?

If you are suggesting capturing video from front or back camera independently, yes that will be supported as the user can just flip the camera inside the camera view. We can add a configuration for which camera to turn on by default. That's a good idea. I'll update the configuration. Thank you

**Comment by kmahmood74** [comment]
@JasPanesar got it, thank you for explaining it. Yes, we will certainly be adding he ability to record video along with taking pictures from the camera. Ensemble is a platform for building front-ends for all types of apps. 

Have you tried it? If not, give it a shot and let us know what you think. https://ensembleui.com and click on Start for Free on top right.

**Comment by vusters** [comment]
@snehmehta please close this if no longer applies after your work.
