### ISSUE TITLE
Notification and deep link handlers at the app level

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1289]
**Problem Statement:**
Our current notification and deep link handling is not right as the handlers need to be specified on the home screen. So when the notification or deep link arrives, it first takes the user to the home screen and from there routes to the right screen. This make the user interaction suboptimal and is also not good developer experience. 

**Proposed Solution:**
App level handlers - 

`Notification Handler` 
 - specified at the app level as a js function. 
 - the js function is in one of the code libraries in the project
 - at the app level there is an optional environment variable
   - `ensemble_notification_handler` - specifies the js function to be called in this format - `<script>.<function>`. For example - `commonUtils.handleNotification`

`Deeplink handler`
 - specified at the app level as a js function. 
 - the js function is in one of the code libraries in the project
 - at the app level there is an optional environment variable
   - `ensemble_deeplink_handler` - specifies the js function to be called in this format - `<script>.<function>`. For example - `commonUtils.handleDeeplink`
   - Deeplink handler will be passed the Deeplink object as a json document
  
**Runtime:**
 Deeplink or Notification handler should be able to run any js code to do logic and return
-  `null` - to specify there is nothing to do
- `error` json object with `{status: error, code: 123, message: 'error message'}` 
- `payload` for the `navigateScreen` action. This payload must have the name of the screen and may optionally also have `inputs`
 
After calling the handler, ensemble framework should read the response and 
- if response is null, do nothing and just load the app as usual. 
- if response is error, show the errorcode and message as toast message. 
- else verify the payload and call `navigateScreen` with the payload.

**Comment by kmahmood74** [comment]
@vusters @vinothvino42 there is more to notifications and deep links than what I wrote above right? how about notification badges, notifications when the app is in the background or foreground? notifications when the app is killed?

Please add comments here

**Comment by snehmehta** [comment]
TODO:-
support deeplink handler as well

**Comment by kmahmood74** [comment]
@sharjeelyunus please review the deeplinkhandler description in the description of this ticket and make sure it captures what you need

**Comment by sharjeelyunus** [comment]
For Deep Link app-level integration make suse it is initialized at app level as well. Right now we can only initialize it at 1 screen, and that doesn't work if the user is on another screen. + If we try to initialize it on more than 1 screen it kind of works for some time but if the user closes the app and opens again it clears the storage i.e user token becomes null and we're back to square 1.

I need to access deep link data on a few more screens like I'm navigating the user to onboarding if the token is null, but in case the token is null and the user comes from deep link then I need to send that data to the APIs as well like the invite_id in those link, so we should be able to access the deep link data on any screen and perform actions accordingly.

For onboarding screen I don't want the navigations automatically, I just need this data to send it to apis and for other screens I want the navigations, so make sure there is a configuration for that.
