### ISSUE TITLE
Dropdown Bugs

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1292]
1. Autocomplete doesn't work with itemTemplate
2. If `autoComplete` is true, value isn't working
3. without autoComplete, the selected text overflows

![image](https://github.com/EnsembleUI/ensemble/assets/61178058/a774c492-4a9c-469b-96b2-80c40ed53ea8)

**Comment by kmahmood74** [comment]
@hemish11 any update here? this is showing in progress, are you working on it?

**Comment by kmahmood74** [comment]
@hemish11 ?

**Comment by sharjeelyunus** [comment]
Include this as well
https://github.com/EnsembleUI/ensemble/issues/1342

CC: @hemish11
