### ISSUE TITLE
Image upload from camera

### ISSUE THREAD

**Issue by jorahul** [EnsembleUI/ensemble#131]
Ability to open camera from within app to take a picture and upload or choose from the picture gallery

**Comment by kmahmood74** [comment]
@jorahul do you just want a camera view and the ability to select pictures or do you also want the ability to scan QR/Barcodes?

**Comment by jorahul** [comment]
Both.

Ability to take a picture or upload one from the gallery to our
application.  Eg. Documents. certificate's etc

Some content like videos we would want the user to view only from within
the app by scanning a QR shared with them.



With Gratitude
Rahul Joshi

**Comment by kmahmood74** [comment]
this was fixed a while ago as part of https://github.com/EnsembleUI/ensemble/issues/128 and is live. 
closing
