### ISSUE TITLE
Regression: GridView is broken on Kitchen Sink

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1320]
See this - https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/DX5j2WVQFabmxD9FCD5h

Specifying multiple values for tile count breaks it. 

However, it works fine here - https://studio.ensembleui.com/app/XIyJyKp0Ck0UBGcRiEF2/screen/CpYZoUy7zqSLPSRvBJ17

**Comment by vusters** [comment]
Fixed. https://github.com/EnsembleUI/ensemble/commit/6e149bc561fa8da0b50073888953e695edd2c617
