### ISSUE TITLE
SportsBracket widget

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1340]
I want to display a bracket widget for sport competitions where:

1. Data is passed as an array of stages (e.g. quarter final, semi final, final), and each array includes array of matches
2. For each stage, matches are displayed vertically
3. Lines connect one stage to another, so user can see which teams might face each other in next round
4. I can pass my custom widgets for displaying stages tab and matches
5. I can set the bracket widget box styling and the connecting lines color and thickness

Example
https://cdn.dribbble.com/userupload/10807499/file/original-06ef59a53e2171e9309f88e3d3acd384.mp4

**Comment by vusters** [comment]
@snehmehta This has to be a separate module. Please move it out.
@amin-nas call this FlowBracket?

**Comment by kmahmood74** [comment]
@snehmehta you moved the bracket to its own package and not to its own module. It is hardcoded inside WidgetRegistry so it can never be removed from pubspec. Please move it to its own module (not just its own package) so it is built only when needed.
