### ISSUE TITLE
Cannot set value on a dropdown with autocomplete

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1342]
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/3tBTU9CUTu0IegpytNYa

See kitchen sink example. The value set on the dropdown is ignored.

**Comment by vusters** [comment]
@hemish11 most likely the same issue as https://github.com/orgs/EnsembleUI/projects/2/views/1?pane=issue&itemId=55714028.
