### ISSUE TITLE
initialized deep link at app level

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1354]
Right now we can only initialize it at 1 screen, and that doesn't work if the user is on another screen. + If we try to initialize it on more than 1 screen it kind of works for some time but if the user closes the app and opens again it clears the storage i.e user token becomes null and we're back to square 1.

I need to access deep link data on a few more screens like I'm navigating the user to onboarding if the token is null, but in case the token is null and the user comes from deep link then I need to send that data to the APIs as well like the invite_id in those link, so we should be able to access the deep link data on any screen and perform actions accordingly.

For onboarding screen I don't want the navigations automatically, I just need this data to send it to apis and for other screens I want the navigations, so make sure there is a configuration for that.

**Comment by kmahmood74** [comment]
is this complete? if yes, please close
