### ISSUE TITLE
Firestore API does not work when passing input to the where clause

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1403]
Test screen:
https://studio.ensembleui.com/app/Qq0BF6CHFWUobsQoZ9Ns/screen/L6fInEWIzTJuXqoGiKIO

1. Run as is and check the console. `getStageMatches` return an empty array
2. Uncomment line 74, which is the stageId for semi finals
3. Now you see two matches returned

**Comment by kmahmood74** [comment]
@amin-nas `stageId` is not being passed as input to the widget and thus not being passed to the invokeAPI call. See the console.log I added to the screen
