### ISSUE TITLE
Controls in `video` widgets.

### ISSUE THREAD

**Issue by TheNoumanDev** [EnsembleUI/ensemble#1407]
The `video` widget doesn't have many properties, I guess we can have a bit more properties to have more control over it like 
- `autoplay` (like the video starts playing on its own when loaded)
- `loop` (it keeps on playing again and again.)
- `navigationButton` (remove the play, previous and forward buttons and have 2,3 values like noButtons, on hover, or always).

![image](https://github.com/EnsembleUI/ensemble/assets/76642732/3fc5f22f-429b-4305-80ac-44c25278a45e)

we could use `Youtube` widget but it is for different use case when we are actually showing YouTube videos in application but when we are just showing videos from random source or just from gallery we don't want that red youtube button to show up and then play with with all these things mentioned over video, like i have also used showControls: false but still things are showing up.

![image](https://github.com/EnsembleUI/ensemble/assets/76642732/9263dd9f-6d44-4555-b2e2-2495a1a2c347)

**Comment by kmahmood74** [comment]
close it if it is not needed @TheNoumanDev
