### ISSUE TITLE
textScale configuration only works on first screen rendered

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1452]
Test app:
https://studio.ensembleui.com/app/QDvclFjagRiXDc1vERJB/screens

Steps:

1. In iOS, increase font size in settings ( Settings > Accessibility > Display & Text Size > Larger Text)
2. Use the test app above to launch starter pointing to the app
3. First screen that loads, accounts for the theme configuration to disable textScaling
4. Click on the button to go to 2nd screen - this screen ignores the textScaling configuration

**Comment by vusters** [comment]
Fixed
