### ISSUE TITLE
dropdown menu styles is required

### ISSUE THREAD

**Issue by TheNoumanDev** [EnsembleUI/ensemble#1458]
In the dark mode,  we need to change the styles more specifically colors of background and text in the menu options and the value that is being seleted as showen in the image below.
![image](https://github.com/EnsembleUI/ensemble/assets/76642732/5e5a329d-ef47-4478-b413-14d91033e0c7)

But lable and floatingLable styles are available.

**Comment by kmahmood74** [comment]
cc @amin-nas
