### ISSUE TITLE
Tab changes when new data is pushed from firebase

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1468]
Steps to reproduce:

1. Create an app connected to a firebase firestore collection
2. Create a screen that has tabbar
3. On first tab, create a widget that is binding to a collection, and listening for changes
4. Now when user is on the second tab, and firetore pushes new data, the UI switches automatically to the first tab

Expected behavior: User should remain on the tab they have selected

Video of the bug:
https://drive.google.com/file/d/1G_Od9jxREeTcez_0WWB4PhTcyUdsY0Pc/view?usp=drivesdk

**Comment by snehmehta** [comment]
View:
  styles:
    scrollableView: true

  header:
    title: Home
  onLoad: |
    ensemble.storage.showConditional = false;

  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:
        - TabBar:
            id: liveTabBar
            styles:
              tabAlignment: center

            items:
              - label: Hello
                widget:
                  Text: 
                    text: Hello
              - label: conditional
                visible: ${ensemble.storage.showConditional}
                widget:
                  Text: 
                    text: conditional
              - label: world
                visible: false
                widget:
                  Text:
                    text: world

        - Button:
            label: Show
            onTap: |-

              ensemble.storage.showConditional = true;
