### ISSUE TITLE
convert from using airtable APIs to mockResponse in kitchen sink

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1473]
many examples are broken. One I ran into is this - https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/fb8d28a2-834e-40a9-8419-155272fb0191

we should not be using the airtable for mocking data anymore

**Comment by jkorn8** [comment]
All airtable API calls replaced with mockResponse. Screens changed are as follows:
- APIs: POST
- APIs: code
- Action: invokeAPI
- ChartJs
- Code: JSON path
- Dropdown
- Form
- Map
