### ISSUE TITLE
regression: showBottomModal over another not working anymore

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1509]
get the following error on console on iOS, works fine on the web - 
```
flutter: Line: 4 in YAML and Line: 4 within the code block. Error Message: Error while executing method: ensemble.showBottomModal({widget:"OtpWidget"}). Underlying error:Looking up a deactivated widget's ancestor is unsafe.
```

This used to work fine and is broken now. 
To reproduce - 

launch app with id: NKxnG7uZBAoxniS4RFL9 on your iphone, works fine on the simulator
tap on login
from the bottom model, enter any phone number or use 925-911-0911
Will remain stuck there. On the web, will take you to the OTP page
This is a regression

**Comment by vusters** [comment]
https://github.com/EnsembleUI/ensemble/pull/1573
