### ISSUE TITLE
Match web's iframe behavior to native's WebView

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#151]
Native's Webview follows this behavior: If height is not set (either explicitly or via expanded), its height will stretch to fit its content's height. We want web's iframe to follow this same direction.

Please test and confirm these 3 behaviors:
1. set explicit height. Scrollbar (if necessary) is within the iframe
2. use expanded with no height. Scrollbar within the iframe
3. no height, no expanded. Height should be as large as content. Scrollbar will be outside of the iframe.

Also confirm the kitchen sink is working as expected https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/22c8d57d-a906-4d11-873d-161fd6c56c0a#

**Comment by hamxa152** [comment]
okay @vusters

**Comment by kmahmood74** [comment]
stale closing
