### ISSUE TITLE
Require custom icon support in ObscureSymbol property in ConfirmationInput Widget

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1537]
![image](https://github.com/user-attachments/assets/13f81e9d-a14b-49e1-b5aa-43c816db36e6)

1) ConfirmationInput widget has default * as it's Obscure Symbol if the Obscure Text is password.
2) We can make the Obscure Symbol Custom to use any other symbol but it can only be text.
3) Requirement is to make a property of creating custom Obscure Image by which we can add our own image as it's Obscure symbol.

Requirements:

Currently what required is that I want to make a filled circle as Obscure Symbol which can't be achieved by current ObscureSymbol property which only supports text.

**Comment by kmahmood74** [comment]
assigning to @TheNoumanDev as he just completed - https://github.com/EnsembleUI/ensemble/issues/1521
@TheNoumanDev provide the support for the obscureSymbol to be an icon and not just text. Icon could be from any supported library.
