### ISSUE TITLE
Require Fix for Conditional Widget, It is is not working.

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1544]
![image](https://github.com/user-attachments/assets/f5e64060-eba4-482a-9d94-ff4883cce8ad)

This is the sample YAML code for Conditional Widget
- First condition is true so IF body should execute
- Second Nested IF Condition is True so IF body should execute
- But I don't see `Nested Conditional Example` text on the screen which clearly Shows that Condition is not working
- If I put the else condition with parent IF and make the condition wrong then Else widget doesn't execute either

**Comment by kmahmood74** [comment]
@snehmehta please close this ticket if resolved
