### ISSUE TITLE
ensemble go: All dropdown values are invisible

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1556]
![IMG_3031](https://github.com/user-attachments/assets/7a21781b-a2a4-4bdf-8c19-7632420d5756)

**Comment by vusters** [comment]
fixed

**Comment by kmahmood74** [comment]
@vusters please link the PR

**Comment by vusters** [comment]
Merged before I realize about this tix https://github.com/EnsembleUI/ensemble/commit/51668e103dbdb5590e0d456c3d21d64a50952c1b.
