### ISSUE TITLE
Downloadable iOS/Android binary for Appstore update

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#158]
Currently users have to follow documentation to build iOS/Android locally https://docs.ensembleui.com/#/deploy/1-prepare-app. We should be automating this process, and users can just download the .ipa (iOS) or .aab (Android) straight from Studio.

Reference:
https://blog.codemagic.io/how-to-build-and-distribute-ios-apps-without-mac-with-flutter-codemagic/

**Comment by kmahmood74** [comment]
part of deployment, lots has changed since, closing as stale
