### ISSUE TITLE
Conditional widget inside Custom Widget + API call losing context somehow and not allowing creating dialogs on response

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1590]
see this - https://studio.ensembleui.com/app/G39hRfg5tj5MozeTLTA7/screen/fhDtnvyB8NEh4RCviC80

and click on the Next button. See error in console.

if you comment out loading `loading: "${MyApi.isLoading}"` under CButton, it works fine. 

```
Error: Overlay is null. 
      Please don't use top of the widget tree context (such as Navigator or MaterialApp) or 
      create overlay manually in MaterialApp builder.
      More information 
        - https://github.com/ponnamkarthik/FlutterToast/issues/393
        - https://github.com/ponnamkarthik/FlutterToast/issues/234
```

Context is coming as DEFUNCT in the api response - 
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/2d13d46f-74bd-40a5-b83c-35f3de506adb">

The moment I comment out `loading` which triggers the conditional widget, context is fine - 

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/1573268f-9e35-41bc-b40e-e26f72988e01">

**Comment by vusters** [comment]
Fixed
