### ISSUE TITLE
Adding custom flutter widget to ensemble studio

### ISSUE THREAD

**Issue by NuzhaKhalid** [EnsembleUI/ensemble#161]
I want to integrate a new flutter plugin that is currently not in the ensemble provided widgets list. How can add it?

**Comment by kmahmood74** [comment]
hi @NuzhaKhalid could you please let us know which plugin you are planning in integrating? Currently it is a bit manual, we will work with you on that. You can also reach me at khurram@ensembleui.com

**Comment by kmahmood74** [comment]
@NuzhaKhalid please let me know, have been waiting for your response

**Comment by kmahmood74** [comment]
dup
