### ISSUE TITLE
Build output APK fails to run

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1610]
Steps to reproduce:

1. Use a project with notifications, camera, file manager, and plaid modules
2. Build an Android APK

cc @kmahmood74 @sharjeelyunus 

The build output runs the app, but is stuck on the splash screen with this error:

![image](https://github.com/user-attachments/assets/8e17fbf5-7b37-4fb3-b919-eeb2bfe9e5f0)

**Comment by kmahmood74** [comment]
please share the ensemble appid @amin-nas

**Comment by kmahmood74** [comment]
this was fixed as part of #1613  and other notification related fixes. Closing.
