### ISSUE TITLE
Need native support for Bluetooth/BLE communication with external devices

### ISSUE THREAD

**Issue by reubensjohn** [EnsembleUI/ensemble#1637]
It would be great if you can provide native support for Bluetooth/BLE communication within the Ensemble framework. The app I am developing has to get data from an external BLE device in real-time

**Comment by kmahmood74** [comment]
@reubensjohn do you need BLE or Bluetooth? the two are quite different

**Comment by kmahmood74** [comment]
both BLE and Bluetooth are needed. Assigning to @snehmehta

**Comment by kmahmood74** [comment]
@snehmehta please add kitchen sink example, documentation and schema for this.

**Comment by kmahmood74** [comment]
what's the yaml for it?
