### ISSUE TITLE
Scrollable TabBar issues

### ISSUE THREAD

**Issue by ridsashabbir** [EnsembleUI/ensemble#1641]
so the Scrollable TabBar is freezing the screen for couple of seconds, and it is throwing errors as `Error :  Bad state: No element` in the console, also this freezing issue is occuring for installed apk as well.
second issue is, visible property is working for normal TabBar and it is not working for Scrollable TabBar
![image](https://github.com/user-attachments/assets/388655fc-c97e-45ec-8c56-d81fc09a879e)

**Comment by vusters** [comment]
Fixed
