### ISSUE TITLE
Popup Menu > I can't access selected item in onItemSelect scope

### ISSUE THREAD

**Issue by Mohammad-Al-Refai** [EnsembleUI/ensemble#1647]
I want to create a list where each item has a three-dots icon. When the icon is clicked, a popup appears with two options: Edit and Delete. However, I am currently unable to determine which option is selected.

**Comment by Mohammad-Al-Refai** [comment]
https://github.com/user-attachments/assets/0674b9de-2242-46c7-be7e-98a61ca58a1c

**Comment by kmahmood74** [comment]
To get the selected value, do this - 

```${event.data.value}```

I just added this [sample](https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/KFOLdHHAi3bRgL0CxHTh)
