### ISSUE TITLE
Dropdown with Autocomplete shows blank entry

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#167]
See screenshot. Dropdown with autocomplete turns on shows blank entry. Typing in doesn't work either.
<img width="919" alt="Screen Shot 2023-01-13 at 11 15 31 AM" src="https://user-images.githubusercontent.com/622269/212400490-dd04f9db-1465-4cb1-8715-0278c00493ce.png">

**Comment by Moeez1999** [comment]
Its Done
