### ISSUE TITLE
Enabling 3 Button Navigation Bar on Mobile phone takes extra space from Bottom

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1671]
- Following are the Images Screen with Enabled 3 Button Navigation Bar:

<img src="https://github.com/user-attachments/assets/24c62eb9-e42c-4b04-ae3e-9875661b561c" width="200" alt="Image 1"> <img src="https://github.com/user-attachments/assets/5225613f-e549-46d1-9e14-409f5b347d08" width="200" alt="Image 2"> <img src="https://github.com/user-attachments/assets/e3570b52-3b64-4287-b13b-218942bea67e" width="200" alt="Image 3">

- Following are the Images without 3 Button Navigation bar:
<img src="https://github.com/user-attachments/assets/d0d57d28-ce42-4975-850b-ab23ba81b74e" width="200" alt="Image 1"> 
<img src="https://github.com/user-attachments/assets/f9b05103-0ee2-4cce-92b2-5f2e4aea6c35" width="200" alt="Image 1"> 

- Problem Explanation:
 When we have 3 Button Navigation bar enabled it takes extra space from the app whereas the screen spacing should be adjusted according to device configurations. In other words, if 3 Button Navigation bar is enabled it should have the same space below the bottom Button as it has without 3 Button Navigation. 
 
 Sample Screen Link:
 https://studio.ensembleui.com/app/v30LUK4wC4uW5t1nkq2o/screen/4s7AqJNyWmW7kGtaKwbN

**Comment by TheNoumanDev** [comment]
The issue occurs when the 3-button navigation bar takes extra space at the bottom of the app, causing layout problems. To fix this, @mehsaandev you need to adjust the height of the parent widget by subtracting the safeAreaBottom, ensuring the layout excludes the space taken by the navigation bar.

For example, you can set the height like height: 
```
FlexColumn:
  styles:
    height: ${ device.height -  device.safeAreaBottom }
``` 
which dynamically adjusts based on the device’s configuration.

This type of problem also happens in Flutter, where we use a similar technique to exclude the safe area at the bottom and prevent UI overlap using `SafeArea` widget.

CC: @kmahmood74

**Comment by kmahmood74** [comment]
@TheNoumanDev have you tested it with and without bottombar on android? seems like the right solution but good to test

**Comment by TheNoumanDev** [comment]
Yup, did tried and below are the result, hope that satisfies the use case, haven't applied styling to it.
![Screenshot_20241008-054309.png](https://github.com/user-attachments/assets/0ab090e9-82c1-46ca-b53e-1caa9c62d1e1)

![Screenshot_20241008-054241.png](https://github.com/user-attachments/assets/8ba9df82-36bd-42ba-bfc8-3448e3ea2a6d)

**Comment by kmahmood74** [comment]
looks great, thank you @TheNoumanDev please document it in the documentation, you can add it as a tip and trick and also ad a bit more explanation here - https://docs.ensembleui.com/utilities/device#properties

good to add an actual picture so users know what we are talking about. We should be using the deviceAreaBottom in all of our apps. I don't think we do. We should definitely use it in Kitchen sink examples

**Comment by TheNoumanDev** [comment]
> looks great, thank you @TheNoumanDev please document it in the documentation, you can add it as a tip and trick and also ad a bit more explanation here - https://docs.ensembleui.com/utilities/device#properties

Yeah sure, will create the documentation for that.

> We should be using the deviceAreaBottom in all of our apps. I don't think we do. We should definitely use it in Kitchen sink examples

Yeah, Amin did use this in `inHome` app as padding, that is how i knew about it but yeah will make kitchen sink example with it as well form now on.
