### ISSUE TITLE
`continue` within a `for` loop can cause browser to hang

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1704]
Test:
https://studio.ensembleui.com/app/9YfZUVl3SC82UZ5Mnf2e/screen/w6mUak1b7RCUazZYIU2f

On this screen, press the button in the footer to run the code. When the code tries to tryParseDouble this speed, it freezes the studio.
```
"speed": "0.0",
```

Note that a standalone example of doing ` "0.0".tryParseDouble() ` works fine.

**Comment by kmahmood74** [comment]
not sure if there are multiple issues but the hanging chrome issue can be worked around by changing the for loop to a while loop

this - 
```js
      var i = pastEntries.length - 1;
      while (i >= 0) {
        //for (var i = pastEntries.length - 1; i >= 0; i--) {
      ...
      i--;
      if (pastTimestamp >= currentTimestamp) continue;
      ...
```
I'll debug the for loop but you should be unblocked by changing it to a while loop
