### ISSUE TITLE
Add iOS/Android camera permissions

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#171]
1. Add camera/microphone/file picker permission to Ensemble_Live. This is how people can preview the camera functions.
2. Update the documentation at Ensemble_docs, showing how users can add the permissions to their Apps. I already have the camera/microphone for iOS. Please follow the same syntax for Android as well as local file permission.

**Comment by kmahmood74** [comment]
@hamxa152 is this done? When checking in, put the reference to this ticket as your git comment. Also close this if this has been completed.

**Comment by kmahmood74** [comment]
@hamxa152 you have the add the permissions to ensemble_live - https://github.com/EnsembleUI/ensemble_live
