### ISSUE TITLE
how to handle the response from the looping card's OnLoad event? The response get overwritten by the last API call.

### ISSUE THREAD

**Issue by gaurikalp** [EnsembleUI/ensemble#174]
### Discussed in https://github.com/EnsembleUI/ensemble/discussions/173

<div type='discussions-op-text'>

<sup>Originally posted by **gaurikalp** January 18, 2023</sup>
As we call the Slot API on the onLoad event of the doctor card, the slot card is overwritten by the previous API call, 
as recorded in the clip.

https://user-images.githubusercontent.com/115991454/213126524-edda71ca-e0e6-4bad-be07-a47ae0f54de7.mp4

</div>

**Comment by kmahmood74** [comment]
@vusters what's the prescribed way to handle this?

**Comment by gaurikalp** [comment]
Yes, By calling the Single API with nested JSON, this problem was fixed.

**Comment by kmahmood74** [comment]
closing as the issue was resolved by making a different call
