### ISSUE TITLE
require `onError` block for openCamera action 

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1746]
There is no way to handle errors if the camera doesn't work or permission is denied.

Regenerating Steps:
- Set up openCamera action on a button.
- Click on that button to open the Camera.
- Deny permission of camera when device asks for permission
- Camera Screen will keep loading infinitely, it'll not go back in case of this error.

**Comment by kmahmood74** [comment]
@snehmehta please update on this
