### ISSUE TITLE
Problem with the date widget: after validating the form, we cannot select the date again.

### ISSUE THREAD

**Issue by gaurikalp** [EnsembleUI/ensemble#175]
### Discussed in https://github.com/EnsembleUI/ensemble/discussions/170

<div type='discussions-op-text'>

<sup>Originally posted by **gaurikalp** January 16, 2023</sup>
- There is problem with the date widget: after validating the form, we cannot select the date again.
- We also cannot set a default date.</div>

**Comment by kmahmood74** [comment]
@gaurikalp this has been fixed, please retest
