### ISSUE TITLE
'copyToClipboard' action is not working

### ISSUE THREAD

**Issue by ridsashabbir** [EnsembleUI/ensemble#1768]
If you attempt this action and try to copy content to the clipboard, it results in an error and fails to copy the content. The error message displayed is:

"Copy is not successful. NotAllowedError: Failed to execute 'writeText' on 'Clipboard': Document is not focused."

![image](https://github.com/user-attachments/assets/138f717b-08b4-4cf6-894c-62031718c3a2)

**Comment by kmahmood74** [comment]
@ridsashabbir does it work on the native device? the error seems to be for web only?

**Comment by kmahmood74** [comment]
also you need to have the focus on the document for the copy to work i.e click inside any textfield and then try copytoclipboard and it will work
