### ISSUE TITLE
Line number for JS errors

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#200]
As an Ensemble app developer, when my JS code snippets contain errors, I want to see a console message that clearly indicates the error and the line number pointing me to the erroneous code.

**Comment by kmahmood74** [comment]
line number for the javascript is relatively easy. It's the line number in the whole yaml that the user is looking for so clicking on the error takes her to that line eventually. @vusters can you get the line number where the code block starts?

**Comment by kmahmood74** [comment]
figured out how to get the line numbers for the yaml nodes. Working on it, should have this done by Tuesday

**Comment by kmahmood74** [comment]
first part is done. Still some open issues such as - 

1. incorrect line numbers for onComplete and global code areas
2. sometimes line number is off by 1
