### ISSUE TITLE
with latest flutter - exception on list with map example

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#210]
upgraded to the latest flutter 3.7+. Everything seems to work fine on kitchen sink except - Layout: Map with List throws an exception.

To replicate
1. upgrade flutter
2. run starter with kitchen sink's app id on Chrome
3. click on 'Map with List'

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/10066434/218366531-02953094-2497-4aad-845e-29b3c4c30492.png">

**Comment by vusters** [comment]
definition fixed.

**Comment by kmahmood74** [comment]
@vusters please describe what was fixed so people would know. Put the yaml here

**Comment by vusters** [comment]
This is using outdated definition. We will be updating the definition.
