### ISSUE TITLE
Widget equal space not working inside a row

### ISSUE THREAD

**Issue by Ammar-Ishfaq** [EnsembleUI/ensemble#211]
Unable to make two or more widgets as equal space in a row

**Comment by amin-nas** [comment]
@Ammar-Ishfaq please see the row example in kitchen sink:
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/4bd0d453-c243-429d-a562-93cbc9db38e3

![image](https://user-images.githubusercontent.com/491202/218475811-246b0208-50da-401a-84ed-0d8cb5f4870f.png)
