### ISSUE TITLE
listView example on the web

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#215]
listView works nice on iphone simulator. 

I changed the example to get rid of stuff around it and remove borders etc as most people will put a listView as the only widget on the page. 

On the web, however, the images from that API don't show up. This is because of the CORS issue. Can you use an API that actually allows the images so our web preview looks good as well. 

![image](https://user-images.githubusercontent.com/10066434/218506817-3bc8dbe3-c414-476a-971e-f4e5b60edc2e.png)
![image](https://user-images.githubusercontent.com/10066434/218506858-f3a50d00-4f80-4132-ac19-58baa4f079ee.png)

**Comment by Moeez1999** [comment]
It is working on web also but i will double check it and if any problem solve it asap

**Comment by kmahmood74** [comment]
@Moeez1999 I know it is working. We need an example for the web where the images show up. See the screen shot I posted from the web please. None of the images are showing up

**Comment by Moeez1999** [comment]
I have updated the ListView so Images are viewing on we also
