### ISSUE TITLE
How to make the custom menu 

### ISSUE THREAD

**Issue by Ammar-Ishfaq** [EnsembleUI/ensemble#237]
how to create a custom menu drawer from a button click

**Comment by kmahmood74** [comment]
@Ammar-Ishfaq could you please share a screen shot of what you are trying to achieve?

**Comment by kmahmood74** [comment]
cc @amin-nas

**Comment by Ammar-Ishfaq** [comment]
@kmahmood74 @amin-nas 

I want to **override** the default close widget with custom as previewed below SS.
![image](https://user-images.githubusercontent.com/54596139/220033340-8cbf528d-fb0d-418b-a385-2572b94f9887.png)

**Comment by kmahmood74** [comment]
from @vusters - 

Basically you can use the built-in close button and position top-left or top-right.
if that is not flexible enough for you. You can do showNavigationIcon: false on the View, and have your own close icon
the close Icon can be something like
```
Icon:
  ..
  onTap:
    action: navigateBack
```
that will pop the screen and behaves exactly like the built-in close button
