### ISSUE TITLE
Some widgets should support Box styling

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#239]
Text, Image, Lottie, QRCode, Carousel, Icon should support Box styling, which includes:

margin / padding
width / height
backgroundColor, backgroundImage, backgroundGradient
borderColor, borderWidth, borderRadius
shadowColor, shadowOffset, shadowRadius, shadowStyle

**Comment by kmahmood74** [comment]
@amin-nas based on our discussion, are doing padding and margin both or just padding? Please update the description.

**Comment by amin-nas** [comment]
Margin only applies to containers. We will add padding to all widgets.

**Comment by vusters** [comment]
All widgets should support Box styling, which includes:
- margin / padding
- width / height
- backgroundColor, backgroundImage, backgroundGradient
- borderColor, borderWidth, borderRadius
- shadowColor, shadowOffset, shadowRadius, shadowStyle
