### ISSUE TITLE
ListView tries to render all items and hangs the app when there are a large number of items

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#247]
@Moeez1999 Your kitchen sink example has the #1 issue below but still is ok as it doesn't have the #2 issue. 

to Replicate - 
login here - https://studio.ensembleui.com/app/e38acc8b-e00f-4c92-a992-1191cc372df8/screen/ONdJ1eqb20w2Y50wer4s
shared credentials with you on slack
then tap on Engineering
Scroll all the way to the bottom and click on Colleges icon from the last card

There are two issues here, both need to be fixed - 

1. ListView creates each child in the list before hand. See this code in ListView class - 

```
  void didChangeDependencies() {
    super.didChangeDependencies();

    if (widget.itemTemplate != null) {
      // initial value maybe set before the screen rendered
      if (widget.itemTemplate!.initialValue != null) {
        templatedChildren = buildWidgetsFromTemplate(
            context, widget.itemTemplate!.initialValue!, widget.itemTemplate!);
      }
```
That causes about 3-5 seconds delay. 

2. The bigger performance issue is that the itemBuilder is called for each item in the list whether it is in the view or not. So in this example, there are over 950 items and itemBuilder is called for each. Therefore there is no point at all in having the list in the first place.

**Comment by kmahmood74** [comment]
cc @vusters Vu, the issue#1 in the description is a list issue but that is not the cause of the major delay. Major delay is due to #2 and that may not be a list issue but of the wrapper around it. See this - https://stackoverflow.com/questions/60624165/listview-builds-all-items-when-inside-another-scrollable-widget

**Comment by Moeez1999** [comment]
Listview was working fine the issue was that i was rendering all the items at the beginning at once and they all build when the listview renders also so that was causing delay at the start
