### ISSUE TITLE
File Upload: example not working on web or iOS

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#250]
There is no progress indicator and it always files to upload file. On the web I get the CORS issue but iOS doesn't work as well

Please provide an example that works

**Comment by snehmehta** [comment]
We are using public mock API service to test file upload and they have small limit for file upload. 
For some reason Flutter web on request fails throws CORS issue. ( I'll dig into it more). 

Also, I have updated uploadUrl service for kitchen sink sample from [beeceptor](https://beeceptor.com/) to [RequestBin](https://requestbin.com/).

Reason been requestBin provide public sharable link to see all request calls. [Here ](https://requestbin.com/r/en09cdal5asztm/2Lzx3lZ071EFF9dFKZCXJTnkJHS) is link for kitchen sink uploadUrl.

_Side Note: Please upload file under 100kb to test or another alternative is to create a local/Live server._

**Comment by kmahmood74** [comment]
thanks for explaining @snehmehta I would suggest the following - 

1. add a textinput field that takes URL to hit. Default should be the requestbin or whichever one we are using. User should be able to change the url and test upload to a different url
2. if default url is selected, add a message as small text - Please upload file under 100kb to test
3. I think we should have another property for uploadFiles action called maxFileSize. That would be important. That way we can catch it and show an error. I'll create another ticket for that enhancement.

**Comment by kmahmood74** [comment]
created https://github.com/EnsembleUI/ensemble/issues/258

**Comment by snehmehta** [comment]
Make sense, will do it.
