### ISSUE TITLE
add Camera action to the schema

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#256]
Schema is here - https://github.com/EnsembleUI/ensemble/blob/main/assets/schema/ensemble_schema.json

To test your schema changes - 

1. Use Visual Studio Code
3. use these instructions for adding custom schemas - https://dev.to/brpaz/how-to-create-your-own-auto-completion-for-json-and-yaml-files-on-vs-code-with-the-help-of-json-schema-k1i
4. point to the ensemble schema on your disk to test

**Comment by vusters** [comment]
@snehmehta please close this if no longer applies.
