### ISSUE TITLE
backgroundColor for form elements

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#260]
* ability to set `backgroundColor` on form widgets such as `TextInput`
* ability to set `backgroundColor` of `Inputs` in the global theme

**Comment by vusters** [comment]
![Screen Shot 2023-02-20 at 11 27 30 AM](https://user-images.githubusercontent.com/622269/220185560-ca2c851c-5db4-4787-b505-b60dc40bc66c.png)
In theme today we can define a variety of styles for Input widget (applicable to the entire App) - see screenshot. BackgroundColor is missing so please add that.

**Comment by kmahmood74** [comment]
closing this as @hamxa152 is done
