### ISSUE TITLE
item-template examples in kitchen sink

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#261]
Add kitchen sink examples for following, one screen per example:

1. Basic example of showing data from an API
2. Example where list is filtered based on an item store in storage

Include descriptions so users learn about the concept of item-templates.

**Comment by amin-nas** [comment]
@sharjeelyunus if you think of other scenarios to cover, please go ahead.

**Comment by sharjeelyunus** [comment]
Added item-template examples here: https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/Pgonai8qVrZZ0fsDT01j#
