### ISSUE TITLE
headers example in kitchen sink

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#268]
Add kitchen sink examples for following, one screen per example. Include descriptions so users just viewing the screen (on preview app) understand the purpose of the screen:

1. Basic header with simple text as the title
2. Header that takes a widget as the title
3. Header that takes a widget for the `flexibleBackground`
4. Header that takes a widget as the title, and include a separate menu icon. Tapping the menu exposes a drawer menu.

**Comment by gaurikalp** [comment]
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/xJ1VaXTmZZvMgw2E3R64
