### ISSUE TITLE
kitchen sink: Modal screen. Clicking on Show Modal shows modal with two close buttons

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#272]
The default for modals is not correct as it shows two close buttons. 

```
the code is simply doing this - 

      -  Button:
          label: Show Modal
          onTap: 
            action: navigateModalScreen
            name: Button
```
but the modal that comes up has two close buttons

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10066434/220493875-43a15fa3-e452-4a17-939e-ff42086c8e1f.png">

**Comment by kmahmood74** [comment]
@vusters feel free to re-assign.

**Comment by vusters** [comment]
Sending this to you @vinothvino42 . The left close button is injected automatically when a modal page has a header, while the right close button also injected for all modal pages. There used to be logic to show one or the other - this has regressed recently.

**Comment by vinothvino42** [comment]
It looks like it's working fine now. I tried with the Ensemble Kitchen App ID ends with `29e6c3dd7992`
