### ISSUE TITLE
Camera - create an example screen to showcase how to use the selected files

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#273]
Create a screen in Ensemble as follows - 

1. Have a button called "Select Images or Videos"
2. Under the button, there should be a ListView widget. ListView should show a custom widget that displays either an image or a video. 

Actions - 
1. Button should call the openCamera action. Max number of files should be 10. Both images and videos could be created or selected from gallery
2. Once user takes or selects photos or videos and closes the camera, take the selected images and videos and add them to the ListView
3. Use the video player if it is a video so I may play the video from the list

User may click on camera many times and select images or videos - all of them should keep getting added to the list view.

**Comment by kmahmood74** [comment]
@hamxa152 feel free to work with @Moeez1999 on this as he created the ListView widget

**Comment by snehmehta** [comment]
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/USuOaOZApSgzE2uVrqlv
