### ISSUE TITLE
Camera - create an example screen to upload selected photos or videos

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#274]
create an ensemble screen with the following widgets and functionality - 

1. TextInput with label - Upload URL. Default should be a free upload service we may use. 
2. Have a button named "Select Images or Videos to upload"
3. Clicking on the button should trigger the openCamera action. User may select existing images or videos or take new ones. Once it closes, use the upload url to upload the selected images or videos. 

This would require chaining two actions - openCamera and then uploadFiles action.

**Comment by kmahmood74** [comment]
@hamxa152 feel free to work with @snehmehta on this as Sneh did the file upload action.

**Comment by snehmehta** [comment]
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/USuOaOZApSgzE2uVrqlv
