### ISSUE TITLE
Sample App: Auto Navigator - clicking on "See All Cars Nearby" display an empty list of cars 

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#276]
Launch app
scroll down to the bottom and tap on "See All Cars Nearby"
this shows up, it's missing the list of cars. Same issue on studio and on Ensemble preview on ios
<img width="376" alt="image" src="https://user-images.githubusercontent.com/10066434/220780445-3a224889-5d27-4d4e-8534-b1cf056527ca.png">

**Comment by sharjeelyunus** [comment]
fixed

**Comment by sharjeelyunus** [comment]
its fixed now

**Comment by kmahmood74** [comment]
@sharjeelyunus please close the issue if fixed
