### ISSUE TITLE
Sample app: appt booking - there is no way to navigate from the View Appointments screen

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#277]
@gaurikalp aftwr a book an appt and then tap on View Appointments, that screen has no bottom bar or menu so I get stuck here. 

There should be the bottom bar, some menu or a nav button so I can go elsewhere in the app 

![7EE4BB2C-AA68-45E0-891E-7F869E155FF4](https://user-images.githubusercontent.com/10066434/220810087-dfcd98eb-7b07-4798-bf9a-029dd43c9a00.png)

cc @amin-nas

**Comment by amin-nas** [comment]
@kmahmood74 this is the issue where the nav goes away even when you navigate to another screen. It should be resolved by fixing how the menu widget works, i.e. keep the menu on the screen unless specified otherwise.

**Comment by kmahmood74** [comment]
works now
