### ISSUE TITLE
Sample app: Appt Booking - clicking on Directions should open the maps app

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#279]
Cc @amin-nas

**Comment by kmahmood74** [comment]
opened #288 as this requires #288 at the platform level first

**Comment by gaurikalp** [comment]
There is https://www.google.com/maps/dir/ used, and it was working on the web.

Is there another syntax to use to access mobile maps, or do you need to ask for permission when building an app?
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

**Comment by kmahmood74** [comment]
stale, closing
