### ISSUE TITLE
Show Preview with selectable device wrapper

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#291]
Wrap the App Preview inside https://pub.dev/packages/device_preview show we can properly show preview for different devices.

**Comment by vusters** [comment]
ensemble_live (Preview) acts both as Studio's Preview (where this change is needed) and standalone iOS/Android Preview app (no need for this wrapper).

**Comment by vinothvino42** [comment]
I just added a preview for the ensemble_live. Can you check if this is fine?


[Video Flow](https://drive.google.com/file/d/1cHFJvI6LFGLeuABx1qgrhO-hre6MDM1o/view?usp=share_link)

**Comment by vinothvino42** [comment]
It is now fixed with PR https://github.com/EnsembleUI/ensemble_live/pull/17
