### ISSUE TITLE
Kitchen Sink - add GridView example

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#292]
Have a GridView example in the kitchen sink.

Here's the 5 responsive breakpoints in the code. We don't have a way to expose this in the theme yet so we have to document this well to the user:
```
  bool isXSmall() => width <= 480;
  bool isSmall() => width > 480 && width <= 800;
  bool isMedium() => width > 800 && width <= 1200;
  bool isLarge() => width > 1200 && width <= 1600;
  bool isXLarge() => width > 1600;
```

GridView's horizontalTileCount can be:
a) 1 number (how many tiles for all breakpoints)
b) 3 numbers (small, medium, large). Xsmall = small and xLarge = large
c) 5 numbers (xSmall, small, medium, large, xLarge).
If not specified, the horizontal tile count is automatic based on resolution.

**Comment by kmahmood74** [comment]
We should change this example to proper GridView - https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/NE42SEc68pQlrULja9iD#

**Comment by amin-nas** [comment]
Removed the old example which was serving as an interim solution.

New screen available here:
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/DX5j2WVQFabmxD9FCD5h
