### ISSUE TITLE
Whenever API bindings are used, 'null' shows up while waiting for API responses

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#300]
This is a very serious problem. See attached video as an example. It happens everywhere and is very noticeable when API responses are slow. 

I don't think anyone can ship any app with this issue and it is prevalent everywhere including our kitchen sink. Is there a workaround? 

https://user-images.githubusercontent.com/10066434/222016693-7298b4c5-1f31-4f0f-b4ea-cf6cefbba30e.MP4

adding another example - 

https://user-images.githubusercontent.com/10066434/222023144-768c200c-2116-454a-828d-6318e65e908e.mov

**Comment by vusters** [comment]
So a bunch of work went in for Image to load gracefully. Unfortunately this is one of those case where we just don't know the exact dimension before the image loads, hence the jerkiness. Our intelli-sense has a warning on this.
<img width="612" alt="Screen Shot 2023-02-28 at 5 26 37 PM" src="https://user-images.githubusercontent.com/622269/222021516-6744b0f0-19e4-4bd3-826c-fc4f0f1a8379.png">

If you try to add the missing width or height, the image will nicely fade in from a random beautiful color. We should publicize the need for width/height (or stretch parent via expanded).

**Comment by vusters** [comment]
For non-Image items, we might have to review them case by case (please list them out if you have). Perhaps the concept of initialValue for the binding will help.

**Comment by kmahmood74** [comment]
@vusters you may be confusing this with a different issue. This has to do with the "null" showing up for a few seconds while the API is being processed. It is caused by the platform executing the bindings without data and affects many apps.

**Comment by kmahmood74** [comment]
dude it affects so many apps that I stopped keeping a count. We can't have a case by case and need a proper general solution. - Auto navigator, Kitchen Sink, Doctor appt app and in fact all customer apps I know have this issue today

**Comment by vusters** [comment]
I got you. I was referring to the UI collapsed then expanded when API returns.

**Comment by kmahmood74** [comment]
added example in the title for the auto navigator app, shows up as null for a while while waiting for API response
