### ISSUE TITLE
Sample App: Auto navigator - nothing shows up when tapping on "Show All Cars Nearby"

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#302]
see video. This is critical, please resolve asap. I kept waiting and the page remains blank. It happens in a bunch of places. Looks like the backend is broken

cc @amin-nas 

https://user-images.githubusercontent.com/10066434/222023449-2fd7c778-113b-46e4-a480-77fffcc3630c.mov

**Comment by kmahmood74** [comment]
actually nothing works on the app. I get a blank page even when I click on any of the car icons. That used to work

**Comment by sharjeelyunus** [comment]
fixed, please check now,
I was trying to use ListView instead of Column, and I guess that caused the problem

**Comment by kmahmood74** [comment]
please make it work with ListView. You may have to use expended: true. Ask @Moeez1999 for help.

**Comment by kmahmood74** [comment]
@sharjeelyunus did the listview work?

**Comment by sharjeelyunus** [comment]
yes, now it's working with ListView
