### ISSUE TITLE
Kitchen Sink - add examples for Date, Time and Flex widgets

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#312]

**Comment by amin-nas** [comment]
Date and Time added
@vusters what does Flex do?

**Comment by vusters** [comment]
Flex can switch between Row or Column using the direction flag. The supported params and behaviors are the same as Row or Column.

**Comment by amin-nas** [comment]
@vusters  Flow also has a direction param, what is the difference?
