### ISSUE TITLE
Examples for string functions

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#338]
Check the array functions supported by Ensemble here:
https://github.com/EnsembleUI/ensemble_ts_interpreter/blob/2be194cf190c01ff5bfeb32597da6c9c42ec8e0a/lib/invokables/invokablecontroller.dart#L212

For any function not documented in kitchen sink, add an example:
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/bf9e503e-286b-437a-a692-14d0d5814918#

**Comment by gaurikalp** [comment]
Added remaining sample for any function not documented in kitchen sink. and raised issues for string function match and matchAll
