### ISSUE TITLE
Integration tests for action "showToast"

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#339]
Add integration tests for action showToast. See existing integration tests.

1. Confirm the 4 different levels of toasts are working with the right message
2. Confirm a custom toast widget will work properly.

**Comment by vusters** [comment]
Add integration tests for action showToast. See existing integration tests.
1. Confirm the 4 different levels of toasts are working with the right message
2. Confirm a custom toast widget will work properly.

**Comment by kmahmood74** [comment]
stale closing
