### ISSUE TITLE
Add integration tests for action "navigateScreen"

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#340]
Add integration tests for action "navigateScreen". See existing integration tests for example.
1. Ensure inputs are passed properly to the next screen.
2. make sure "replaceCurrentScreen" is working (e.g. clicking back doesn't take you to previous screen)
3. make sure "clearAllScreens" is working (e.g. the back button doesn't appear)

**Comment by vusters** [comment]
Send this over to you @vinothvino42 . Can you look over the pending PR https://github.com/EnsembleUI/ensemble/pull/367? It is for this issue but not yet completed. See if you can either continue / modify / or start a new PR.

**Comment by kmahmood74** [comment]
stale closing
