### ISSUE TITLE
Action NavigateBack/closeAllDialogs doesn't work without making it an object

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#350]
Action currently has this syntax:
```
Button:
  onTap:
    invokeAPI:
      ...
```
But it also has a short-and notation for writing code.
```
Button:
  onTap: |
    //@code
    <javascript code here>
```
In the 2nd example we detect if the Action is a plain string, then we assume it is code. This is invalid however as action `NavigateBack` doesn't take any parameter so technically you should be able to write this:
```
Button:
  onTap:
    NavigateBack
```
This will cause the system to mistakenly think the action is ExecuteCode instead of NavigateBack (workaround is to have a semicolon afterward to make it an Object, but no one would be doing this). We need to fix this problem for both `NavigateBack` and `closeAllDialogs`

**Comment by evshi** [comment]
Should it only accept `navigateBack` (camelCase) instead of `NavigateBack` (TitleCase)? The existing keys for the actions only accept camelCase at the moment.
