### ISSUE TITLE
ListView's onItemTap doesn't work as expected

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#355]
See kitchen sink https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/w0Wmu9ZMP4csk7IELSx3#

onItemTap should work by clicking anywhere on the tile, but it only works if you select on the title/subtitle/photo

**Comment by vinothvino42** [comment]
Fixed it in this PR - https://github.com/EnsembleUI/ensemble/pull/684
