### ISSUE TITLE
Is Kitchen Sink Finicity working as expected?

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#361]
Is this Kitchen SInk page working as expected ?
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/a97b5f0f-c90d-47b3-88f2-980e69778678#

**Comment by kmahmood74** [comment]
It works but now with the new preview, the popup bleeds out of the screen. We won't be fixing this as it's not been used.
