### ISSUE TITLE
Validate the widget from schema before creating it

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#364]
Today if we pass a widget as a setter property, we have to blindly take it in as dynamic. When we actually build the widget (later in the build cycle), only then we would figure out if it is a valid widget or gibberish. The proposal here is to validate it at the setter so we can warn the user. We can check at least the following:
1. is it a valid widget (e.g. "Column" or "Grid" or. ...)
2. is it a custom widget that the user defined.

**Comment by kmahmood74** [comment]
done, closing
