### ISSUE TITLE
Gap doesn't work with Custom Widget

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#393]
When Custom Widget is a child of a Column/Row, gap doesn't work.
https://studio.ensembleui.com/app/88a4d904-86a5-4c8c-a8be-5d606660b545/screen/5670433c-919f-4d08-81b3-35c36bccf8b2

**Comment by vinothvino42** [comment]
Looks like the link is broken @vusters

**Comment by vinothvino42** [comment]
PR #397 is merged now. Closing it
