### ISSUE TITLE
Docs - API Reference for Ensemble

### ISSUE THREAD

**Issue by vinothvino42** [EnsembleUI/ensemble#400]
Create an **API Reference** for the ensemble project. It's really hard to find out all the APIs in the editor itself, having an API reference doc is a good thing.

Writing a single command `dart doc .` in the root directory will create docs for us.

Please refer the following links
https://dart.dev/tools/dart-doc
https://pub.dev/packages/dartdoc

**Comment by kmahmood74** [comment]
later
