### ISSUE TITLE
Selecting text causes rendering of the page to break

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#406]
See attached video.

https://user-images.githubusercontent.com/491202/229380181-fdc48804-3286-459e-b249-7b60c148e107.mp4

**Comment by evshi** [comment]
I think best path forward in short term would be to scope the selectable text to specific widgets instead of trying to apply globally to the screen. Long term we should try and understand why our widget structure would cause flutter to behave this way.

**Comment by kmahmood74** [comment]
@amin-nas is this still an issue? please assign if it is

**Comment by vusters** [comment]
@snehmehta  can you fix this issue in Web. Please see the previous issue when we attempted to do this. Let's do it only for Text widget, and we can add others as needed.

**Comment by snehmehta** [comment]
previous issue: https://github.com/EnsembleUI/ensemble/issues/368

**Comment by kmahmood74** [comment]
@snehmehta just run kitchen sink, appid: e24402cb-75e2-404c-866c-29e6c3dd7992
with this change, none of the buttons even on the first page are clickable

**Comment by amin-nas** [comment]
this has been fixed
