### ISSUE TITLE
Unable to set a dynamic source for the column's background image

### ISSUE THREAD

**Issue by gaurikalp** [EnsembleUI/ensemble#411]
We are unable to set a dynamic source for the column's background image.

**Comment by gaurikalp** [comment]
body:
    FittedRow:
      styles:
        mainAxis: spaceBetween
        padding: 5 5 12
        childrenFits: [1 , auto]
        crossAxis: center
        gap: 16
      children: 
        - Dropdown:
            styles : { expanded: true}
            id: typeInput
            icon: search
            hintText: What would you like to eat?
            autoComplete: true
            items:
              - Pizza
              - Burger
              - Thai
              - Chinese
              - Korean
              - Noodles
            value: All
            required: true
            onChange:
              invokeAPI:
                name: getFoodList
                inputs: 
                  term : ${this.value}
                  location : "US"
        - Column:
            onTap:
              executeCode:
                body: |
                  //@code  
                    clearLocation();
                    typeInput.value = '';
                    ensemble.invokeAPI('getFoodList',{'location': "US",'term': "food"});
            children:
              - Text:
                  text: Cancel
                  styles: 
                    color: orange

**Comment by kmahmood74** [comment]
it's the well known issue with nested bindings.
