### ISSUE TITLE
Background Uploading Service

### ISSUE THREAD

**Issue by Ammar-Ishfaq** [EnsembleUI/ensemble#418]
Image/video should have to be uploading in the background as their size may be large.
when the user press uploads the uploading should be moved to the background process where it generates a notification or flag for the frontend to know that the uploading is in progress, and we can show a msg on UI to the user.
when the task gets finished a notification will pop up that the Image/Video uploaded successfully.

Endpoints will be shared privately

**Comment by kmahmood74** [comment]
assigning to @snehmehta Hi Sneh, could you please work on this as highest priority. Thank you so much.

**Comment by snehmehta** [comment]
Okay, on it.

**Comment by kmahmood74** [comment]
@snehmehta please provide - 
1. Kitchen sink example
2. Documentation on the [ensemble docs repo ](https://github.com/EnsembleUI/ensemble_docs)

**Comment by kmahmood74** [comment]
please close this if this is complete
