### ISSUE TITLE
Column's gap still doesn't work

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#427]
Column's gap still doesn't work with the latest code https://studio.ensembleui.com/app/88a4d904-86a5-4c8c-a8be-5d606660b545/screen/5670433c-919f-4d08-81b3-35c36bccf8b2

**Comment by vusters** [comment]
@vinothvino42 can you please look into this regression?

**Comment by vinothvino42** [comment]
Can you give me access to it? @vusters

**Comment by vinothvino42** [comment]
Got it, it's the problem when using Column or any flex widgets with `item-template`

It's now fixed with PR #436
