### ISSUE TITLE
BottomNavBar items can be offset outside of its' boundary

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#435]
![Image](https://user-images.githubusercontent.com/622269/231537544-c69e9729-029f-4202-a042-960b3768027d.jpeg)
For each BottomNavBar item, the user can move the item vertically outside of its parent's boundary. Horizontally it should be placed how it is today, so the horizontal spacings between it and other items are consistent.

**Comment by vinothvino42** [comment]
@vusters Can you review this code? https://github.com/EnsembleUI/ensemble/commit/8e26e7b26511c9a9453fbc9eb1c05c44636f8798

**Comment by kmahmood74** [comment]
done, closing
