### ISSUE TITLE
Device Preview doesn't respect SafeArea

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#445]
When device preview is using an iphone with the notch, it should respect the SafeArea.

![Image](https://user-images.githubusercontent.com/622269/233443183-520c1427-f36a-4396-aa7b-4fdafd9a4da8.png)

**Comment by vusters** [comment]
@vinothvino42 please also update the background color (when in Device Preview) to the same color as Studio

**Comment by vinothvino42** [comment]
@vusters Is the device frame need to be aligned top center? In the device preview implementation, it's added padding on all four sides with 20 + viewPadding

**Comment by vinothvino42** [comment]
@vusters I updated the device preview background color

![Image](https://user-images.githubusercontent.com/12869588/235598258-b697e8b0-cac6-4ff5-a6e5-2a42c07617cc.png)

**Comment by vusters** [comment]
looks good. Please merge. The preview is still too small for me but OK until we have another opinion. Please close this.
