### ISSUE TITLE
Need more data when we connectWallet

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#459]
at this time we're just getting the address of the wallet when we use connectWallet, need more data to make it useable like balance, image, and a few more things
In intellisense it suggest walletConnect, the correct word is connectWallet

**Comment by snehmehta** [comment]
@sharjeelyunus 
Both image and balance are not part of wallet connect.

To get balance we need to use particular network provider e.g for ethereum we can use https://docs.etherscan.io/api-endpoints/accounts.

For image we can do something funky using service like avataars https://getavataaars.com.

**Comment by kmahmood74** [comment]
not needed at this time
