### ISSUE TITLE
Control spacing between button label and icon

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble#462]
https://discord.com/channels/1031982848485359626/1102753903734431794/1102753903734431794

https://github.com/EnsembleUI/ensemble/pull/358#discussion_r1139023000

**Comment by kmahmood74** [comment]
@amin-nas @sibteali786 can we use padding/margin for this?

**Comment by sibteali786** [comment]
isnt this issue resolved by gap property for the button [here](https://docs.ensembleui.com/#/widget-reference/button)
