### ISSUE TITLE
Enable setting widget styling props from theme

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#463]
For all props defined under styles, I expect to be able to set them from the theme.

Priority:
1. Button
2. Text
3. Divider
4. Switch
5. Dropdown
6. Progress
7. TabBar
8. All remaining widgets

**Comment by kmahmood74** [comment]
@amin-nas this is done with @snehmehta 's theme changes right?

**Comment by amin-nas** [comment]
@kmahmood74 negative
