### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#48]

**Comment by amin-nas** [comment]
Start by suggesting the YAML for this widget.

**Comment by kmahmood74** [comment]
@hamxa152 as Amin suggested, the first step, please suggest the YAML for the widget and tag me in the comment. Once we approve the YAML, you can start implementing. When you are working on something, please put that in progress.

**Comment by kmahmood74** [comment]
assigning to Sneh as he is already working on it

**Comment by snehmehta** [comment]
Checked in with https://github.com/EnsembleUI/ensemble/pull/692
