### ISSUE TITLE
Scope of the variables and functions

### ISSUE THREAD

**Issue by gaurikalp** [EnsembleUI/ensemble#483]
What is the Scope of the variables and functions, such as local and global, is also difficult to find.

Since we understand that -
"global" var or functions are available/accessible on all screens.
local var accessible for that screen only.

We experienced problems increasing or adjusting counter values while displaying story parts in the social app.

**Comment by kmahmood74** [comment]
@gaurikalp I think this is due to this blocked issue - https://github.com/EnsembleUI/ensemble/issues/447

Globals are supposed to be global on that screen only but do not work properly due to the bug above

**Comment by kmahmood74** [comment]
answered
