### ISSUE TITLE
Weather App takes a very long time to display

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#496]
The load time is ridiculously long
It's probably the location that is taking far too long. 
can we improve the experience?

https://studio.ensembleui.com/app/IjZZeDQTaAvDgnHWVPs7/screen/gBrOpcu3gOxW9v35LLKm

**Comment by amin-nas** [comment]
Defaulting to NYC weather so there is no wait time. User can click on the button for Get Current Location to get local weather.
