### ISSUE TITLE
Navbar icons without labels

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#505]
## Bottom Navbar 
The icons in the Navbar menu are always needed to have labels which is not always the case. In my case screen, there is no need for labels just icons are enough. 
### Snap
![image](https://github.com/EnsembleUI/ensemble-web-studio/assets/62849614/5372c618-5d9c-4f15-b19c-ad643b9311f4)

- Plus having custom icons is also needed like the one on the right-most in the image is a profile picture.
- Both Drawer and bottomNavBar should be able to be put together in a single screen because for now, I guess we cannot add both only either of them can be used.

**Comment by kmahmood74** [comment]
@sibteali786 is this still an issue?

**Comment by sibteali786** [comment]
after custom widgets for menu items , not an issue anymore. Should i close it now

**Comment by kmahmood74** [comment]
closing
