### ISSUE TITLE
TabBar should be customizeble 

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#515]
TabBar Items should be customizable just like the BottomNavBar items

- SelectedItems and InactiveItems can be made customizable just like BottomNavBar where we can use custom widgets

### Some Examples
![image](https://github.com/EnsembleUI/ensemble/assets/62849614/ccc35693-196d-4e38-b790-4ff6b884629e)
![image](https://github.com/EnsembleUI/ensemble/assets/62849614/0622749b-e7ee-4c71-9208-316ce38fb279)

**Comment by kmahmood74** [comment]
@amin-nas comments?

**Comment by amin-nas** [comment]
ability to make tab items a custom widget is added:
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/cebd491d-7d90-43f4-9f17-b8575de441ca
