### ISSUE TITLE
Not being able to choose Data in item-template 

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#519]
Somehow the highlighted code is not working as it should. I'm using ternary operator for choosing the Data for item-template i.e., if ensemble.storage.followSymbols array is empty, then use api result getSymbols.body.symbol else use ensemble.storage.followSymbols

![239311718-fa1d510f-45d1-46f9-95c7-e60938f378cf](https://github.com/EnsembleUI/ensemble/assets/32386713/e03d80b8-e72a-4b69-b8e2-2f354209829a)

I have tried console logging in onLoad of this screen
- ensemble.storage.followSymbols               returns []
- ensemble.storage.followSymbols.length    returns 0

This is how I'm initializing followSymbols array:

```
Global: |
  //@code
  if (ensemble.storage.followSymbols == null) {
    ensemble.storage.followSymbols = []
  }
```

link for the screen: (stockline app)
https://studio.ensembleui.com/app/PqiJYbUHUb0gGeiKqBC2/screen/cGiKcKKqqW3rKt8vAcbE

**Comment by kmahmood74** [comment]
I'll check it out first

**Comment by anserwaseem** [comment]
link for the screen: (stockline app)
https://studio.ensembleui.com/app/PqiJYbUHUb0gGeiKqBC2/screen/cGiKcKKqqW3rKt8vAcbE

**Comment by kmahmood74** [comment]
this was fixed, please check again and reopen if needed
