### ISSUE TITLE
Dropdown is not accessible in test scripts

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#530]
![image](https://github.com/EnsembleUI/ensemble/assets/491202/4417f9a5-7ae4-4750-aa06-f1cac56ffcfe)

**Comment by vusters** [comment]
@snehmehta can you help with this?
It's also a bit cryptic for folks to write unit tests based on our widget, so think about how to solve this for later too please.

**Comment by snehmehta** [comment]
aye aye captain
