### ISSUE TITLE
Unable to run forked repo of Ensemble Starter

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#532]
We have a customer repo that is a clone of Ensemble Starter. Since recent changes for preview, I am unable to run it.

![image](https://github.com/EnsembleUI/ensemble/assets/491202/40ebc688-4ee9-4417-bf12-4edbf7d9fc64)

**Comment by vinothvino42** [comment]
I updated the ensemble's device preview functionality and updated the ensemble_starter_kpn [PR](https://github.com/EnsembleUI/ensemble_starter_kpn/pull/24)
