### ISSUE TITLE
Or operator not working in Javascript code

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#534]
I have a function which is using an OR operator || in Javascript code but it's not working:

code:
```
Global: |-
  function getWeekday(numDay) {
    console.log("numDay = "+numDay)
    if (numDay == 1 || numDay == 8) {
        return "Mon";
    } else if (numDay == 2 || numDay == 9) {
        return "Tue";
    } else if (numDay == 3 || numDay == 10) {
        return "Wed";
    } else if (numDay == 4) {
        return "Thu";
    } else if (numDay == 5 || numDay == -2) {
        return "Fri";
    } else if (numDay == 6 || numDay == -1) {
        return "Sat";
    } else if (numDay == 7 || numDay == 0) {
        return "Sun";
    } else {
        return "";
    }
  }
```

screen in which i'm using this https://studio.ensembleui.com/app/TQP5125dbdMgNdDpKzWz/screen/nq1rWjhPHCHfIfksuVyN

Although it's working fine on an online compiler
![image](https://github.com/EnsembleUI/ensemble/assets/32386713/e43ca2b4-432e-4c08-9a6b-c598d8d45b67)

**Comment by kmahmood74** [comment]
good catch, it was a bug in my code. Just checked in the fix. 

@amin-nas requesting a studio rebuild. The fix was in the interpreter

**Comment by kmahmood74** [comment]
https://github.com/EnsembleUI/ensemble_ts_interpreter/commit/230527d6994e6576b878a5102797e9e00e5114a8
