### ISSUE TITLE
Saving definitions in Studio doesn't update Preview properly

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#538]
Two separate issues:

1. Saving the definition in Studio reload the Preview, but the Preview's Flutter code still have the same code as before the Save. You have to reload the browser for it to change.
The Preview should have a UniqueKey() so it always reload the content. This might have been compromised with the latest changes

2. When entering text and the keyboard slides up, the background content is resized. The previous and correct behavior is that the keyboard will slide above the content.

**Comment by vinothvino42** [comment]
Keyboard issue is fixed - #540

**Comment by kmahmood74** [comment]
both issues have been fixed, closing
