### ISSUE TITLE
Styling for TextInput not working

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#546]
I want the add a border or outline around the TextInput and PasswordInput, but noting seems to work, even added the backgroundColor and that's not working

![Image](https://github.com/EnsembleUI/ensemble/assets/61178058/5789e3c7-8183-45e2-9ee7-14b451853963)

**Comment by snehmehta** [comment]
@sharjeelyunus their no property for like backgroundColor, I believe you are looking or fillColor, outline is also not a property.
Lastly, I see some issue in borderColor, which will be added soon in PR https://github.com/EnsembleUI/ensemble/pull/518

**Comment by kmahmood74** [comment]
closed as answered and done
