### ISSUE TITLE
BottomNavBar styling for dark mode and spacing

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#552]
Issue 1 - dark mode: when setting the background of navbar to a dark color, there's still a white space around the floating button. I expect that space to be transparent.

<img width="373" alt="Screenshot 2023-06-01 at 7 18 17 AM" src="https://github.com/EnsembleUI/ensemble/assets/491202/759fff65-dc4a-4847-b779-dec215033ddf">

issue 2 - spacing: when using 2 nav items and the floating button, I expect the space to be distributed evenly. It looks like the two nav items are spaced to the two edges. If I can set the padding of the nav bar container, I can control the spacing for this use case and other use cases as well.

<img width="372" alt="Screenshot 2023-06-01 at 7 20 04 AM" src="https://github.com/EnsembleUI/ensemble/assets/491202/32b6d078-da70-405a-96e5-3d1046ae1d6e">

**Comment by vinothvino42** [comment]
@amin-nas It is fixed in this PR #558
