### ISSUE TITLE
Investigate iOS app and Safari extension linkage

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#554]
Investigate whether within an iOS app (built with Ensemble) we can detect and exchange messages with a Safari mobile's extensions.

Detail Flow:
- User opens the iOS app built in Ensemble
- User is prompted to download and install a mobile Safari extension
- User clicks yes which opens Safari - this is outside Ensemble
- User installs the extension or doesn't and is redirected back to the iOS app built in Ensemble
- iOS app detects if the extension is there or not and prompts the user if not.

Apparently this is well supported in iOS - https://developer.apple.com/documentation/safariservices/safari_web_extensions
also there is a way to send messages from javascript in safari web extension to the ios app - https://developer.apple.com/documentation/safariservices/safari_web_extensions/messaging_between_the_app_and_javascript_in_a_safari_web_extension

**Comment by vinothvino42** [comment]
@vusters Here's the ensemble safari extension starter project - https://github.com/vinothvino42/ensemble_extension_starter

**Comment by kmahmood74** [comment]
link to the ensemble repo for extension - https://github.com/EnsembleUI/ensemble_extension_starter
closing it as Vinoth is done with it
