### ISSUE TITLE
unable to preview a re-usable widget (shows the oh snap error)

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#562]
<img width="1436" alt="image" src="https://github.com/EnsembleUI/ensemble/assets/10066434/a0497909-073e-4d71-82fe-9cf260a06c6c">

https://studio.ensembleui.com/app/541d7525-31f7-4c6d-9f06-74fb07c2cacc/widget/zCcYmFP4udOS6KclpmCM

@amin-nas not sure who to assign it to, starting with you, feel free to re-assign

**Comment by amin-nas** [comment]
Seems to be from flutter side. @vinothvino42 - please take a look.

**Comment by vinothvino42** [comment]
@amin-nas  @kmahmood74  It is fixed in this PR #578
