### ISSUE TITLE
Need Container widget

### ISSUE THREAD

**Issue by vinothvino42** [EnsembleUI/ensemble#568]
Now even for one child with `background`, `padding`, `borderRadius` background. I need to wrap my child with `Column` widget. It would be nice to have something like below for a single widget to have those common properties.

```dart
Container:
  styles:
    backgroundColor: 0xFF282A33
    padding: 12
    borderRadius: 40
  child:
    Icon:
      styles:
        color: white
      icon: local_mall
```

**Comment by vinothvino42** [comment]
> @vinothvino42 we discussed this issue before and decided to expose those properties on all widgets. E.g. you can pass backgroundColor, padding, and borderRadius to an Icon widget. Do you see a gap in the current approach?

Is this approach implemented now?

**Comment by amin-nas** [comment]
Yes, for majority of widgets. If there are gaps, please open tickets so we can address them.
