### ISSUE TITLE
boxStyles being referenced incorrectly for many widgets

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#577]
The boxStyles properties are being referenced in many of the widgets as in json schema but sometimes not all of them are correct for instance Image widget styles show backgroundImage, backgroundColor etc under its styles which makes no sense at all.
Note: need some suggestions to correct as i am already working on adding and improving existing properties in both docs and json schema.
cc: @amin-nas @vusters @kmahmood74

**Comment by amin-nas** [comment]
I dont see why this is an issue. Images can have transparent backgrounds, then you can use the style properties to create layers. Here's an example:

<img width="1290" alt="Screenshot 2023-06-14 at 9 28 26 PM" src="https://github.com/EnsembleUI/ensemble/assets/491202/fa85f4c3-9ed5-479c-bc78-a1331b1d8c0c">

**Comment by sibteali786** [comment]
ok so i guess it should be there, thanks for the clarification.
