### ISSUE TITLE
TextInput properties for minLines and maxLines

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#58]

**Comment by sarge-universily** [comment]
We are adding a long text field to hold either 150 or 350 words for an input form to allow editing of their activity description.

**Comment by sarge-universily** [comment]
![image](https://user-images.githubusercontent.com/81441011/197637562-da135752-918b-4a28-92f0-7f636e248d41.png)

**Comment by kmahmood74** [comment]
already completed - maxLines is supported. https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/abc081b1-bcb4-4db6-ae55-7987cb6c418e

No use case for minLines yet. Closing as completed.
