### ISSUE TITLE
EnsembleAction should evaluate its value upon the action taken place

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#604]
Currently we evaluate the inputs to EnsembleAction while constructing the action. This is incorrect as the value should only be evaluated `when` the action is taken (e.g. onTap).
Refactored all Actions to ensure:
- really only action id should be raw and not be evaluated, pretty much every other values should be evaluated, and evaluated when the action is taken.
- When calling Action.fromYaml() we should just take value in as-is.
- When executing the Action, that's when the evaluation should take place. Try to do this inside the Action to not clutter up ScreenController

**Comment by kmahmood74** [comment]
@vinothvino42 this has been in progress since June 26th. Please update progress here

**Comment by vinothvino42** [comment]
@kmahmood74 @vusters  Updated a few more actions. Check PR - https://github.com/EnsembleUI/ensemble/pull/613

**Comment by vusters** [comment]
@vinothvino42 please abandon this review. Too much changes have since merged in, plus I have changed how Actions work.
