### ISSUE TITLE
Theme's Text theme font color always white unless overriden

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#609]
When define any attribute in theme's, the font color changes to white:
```
Text:
  bodyMedium:
     fontSize: 40    # anything attribute will have the color as white (unless you use color of course).
```
I saw other code hardcode the color to Black. You shouldn't need to do this if we are using the light theme (color shouldn't be white by default on light theme).

**Comment by snehmehta** [comment]
I got to take deep dive to understand it as well. 

But that the case, if we pass null as color default it's taking white color and that is the reason I hardcoded black in default style and similarly assigning fallback style color to custom style. here is [PR](https://github.com/EnsembleUI/ensemble/pull/876) of it.
