### ISSUE TITLE
Device keyboard to push content up

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#623]
When device keyboard is exposed, the view's height should adjust to available space so that app developer can control the positioning of widgets.

![keyboard](https://github.com/EnsembleUI/ensemble/assets/491202/b67a88ac-1bb8-4127-82d0-378e34edb68a)

**Comment by vinothvino42** [comment]
@amin-nas Created a PR - #636

**Comment by vusters** [comment]
Resize the screen causes a lot of jittery and sizing issue, especially when a background image is used. Would this makes more sense to put the button in this case (any widget normally) to the footer, and we make footer always move with the keyboard?
@vinothvino42 @amin-nas thoughts?

**Comment by amin-nas** [comment]
That satisfies the use case of moving the content. 

Given part of the body would be covered by the keyboard, would user be able to scroll and reach that content?

**Comment by vusters** [comment]
User can dismiss the keyboard and scroll. @vinothvino42 can you implement what I said above?

**Comment by vinothvino42** [comment]
@vusters  I created a PR - https://github.com/EnsembleUI/ensemble/pull/647

But what if I have some forms in the body of the view and having footer with some submit button. Now I can able to move the footer (button) but it hides the form fields right?

<img src="https://github.com/EnsembleUI/ensemble/assets/12869588/280fc290-aac9-45c8-9d88-0af094f5c437" width="350" />
