### ISSUE TITLE
Ability to access device contacts

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#626]
I want to be able to prompt user to provide access to device contacts, and get contact list upon user granting access.

**Comment by vinothvino42** [comment]
@vusters @amin-nas 
Sample **YAML**

I am using https://pub.dev/packages/fluttercontactpicker/ flutter package, which shows a native contact picker.

```dart
Button:
  label: Pick Phone Contact
  onTap:
    pickPhoneContact:
      id: phoneContactId
      options:
        linkToken: ${getLinkTokenFromServer.body.linkToken}
      onSuccess: |
        //@code
        console.log("Contact fetched successfully");
        console.log(event.data);
        console.log("Phone Number" + event.data['phoneNumber']);

      onExit: |
        //@code
        console.log("Something went wrong!");
```

**Comment by amin-nas** [comment]
@vinothvino42 - I want to be able to get the full contact list so that I can display them with Ensemble widget of my choice. Here's an example:

![Invite Friend - post permission](https://github.com/EnsembleUI/ensemble/assets/491202/77be56af-a806-44bb-b42f-690676f5e59b)

**Comment by vinothvino42** [comment]
Okay @amin-nas Then I'll use this package instead - https://pub.dev/packages/flutter_contacts
Here, you need to use your own view to populate all the contacts

**Comment by amin-nas** [comment]
@vinothvino42 we use `onAccept` and `onReject` for notification access request. Let's change the above to be consistent.

cc @vusters

**Comment by vinothvino42** [comment]
@amin-nas I think we've used `onSuccess` in other widgets too.
