### ISSUE TITLE
Header's backgroundColor and margin/padding

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#631]
Header enhancements:

- Enable setting padding: 0 - there is built in padding that user cannot control.
- Enable setting backgroundColor when user scrolls . Currently a color is auto-set depending on seed color and user cannot change it.
![image](https://github.com/EnsembleUI/ensemble/assets/62849614/37199261-c998-43ec-a364-a6d67087e3ad)
![image](https://github.com/EnsembleUI/ensemble/assets/62849614/281e6344-a233-4bec-b2b6-6508cc927ec3)

**Comment by snehmehta** [comment]
@sibteali786 can you please add me as collaborator 
sneh@ensembleui.com

**Comment by sibteali786** [comment]
@snehmehta sent you invitation

**Comment by snehmehta** [comment]
Thanks! @sibteali786
