### ISSUE TITLE
Custom label needed to use in ChartJs thorough a third party plugin  

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#642]
This [plugin](https://chartjs-plugin-datalabels.netlify.app/) allows us to add custom labels within the Doughnut chart in ChartJS. Although it still lacks the existence of icons in tags but does 50% work of the custom label requirement we have in a design. 
Design Required 
![image](https://github.com/EnsembleUI/ensemble/assets/62849614/c37fc76c-fcbe-41e7-9f69-015666c01fe2).

If we can somehow integrate it in ChartJs ensemble it will be helpful.

**Comment by kmahmood74** [comment]
@sibteali786 is this already done as I saw it in a demo?

**Comment by sibteali786** [comment]
@kmahmood74 yeah its already done no need for third party plugins .
