### ISSUE TITLE
Need number as inputType in TextField widget

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#669]
As seen from the screenshot attached, there's no way to restrict user for only numeric values. Please add number/numeric inputType for TextField.

![image](https://github.com/EnsembleUI/ensemble/assets/32386713/2d5b4357-e901-4b6a-9a0d-3751f9d74495)

**Comment by vusters** [comment]
Remember to add the validator for each inputType we support. It is not just the visual keyboard.

**Comment by vinothvino42** [comment]
It's completed. PR - #676
