### ISSUE TITLE
Static Analysis to automatically include a module

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#673]
https://github.com/orgs/EnsembleUI/projects/2?pane=issue&itemId=34097191 describe the module inclusion based on a config file. We can do this by scanning the YAML definitions. If there is the presence of e.g. camera, we can have a script on Starter to automatically generate the pubspec/EnsembleModules to include e.g. ensemble_camera module.

**Comment by kmahmood74** [comment]
we should not do this, including a module should be an explicit user action
