### ISSUE TITLE
Improve local assets

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#678]
Background:
Today in Studio you can define key/value pairs of Environment Variables. When deployed with Starter, you can override these values within your ensemble-config.yaml. This is how we do generic Dev/Production variables.

Local Assets leverage this to load images via URL (with Studio), but embed these images via resource string (with Starter). This allows the rapid prototyping in Studio, but enable fast image loading locally when deployed.

Improvements:
1. Erroneous and extra slash should be ignored, e.g. `${env.myFolder}/image.png` should work even if myFolder is defined as `/assets/` (ending with slash).
2. If the local path is specified as `ensemble/images/`, this will be the exact root to append to the files. Previously we also append this path to `ensemble/assets/*`. In another word, if the user specify null or empty it'll use the default root. If they specify a non-empty value, that will be the root.
3. The problem is currently we assume that the image name (e.g. my_book.png) is the same on both Studio and Production. The YAML definition may define the image source as:
```
Image:
  source: ${imageDirectory}/my_book.png
```
In Studio, we define `imageDirectory=https://images.google.com/abcd`.
In Starter, we override it with `imageDirectory=/ensemble/assets`.

This won't work if the image name is not the same name. We should improve it so that we have the flexibility of different image names.

**Comment by snehmehta** [comment]
@hemish11 So, local assets for building application, make sure you go through this issue first

**Comment by kmahmood74** [comment]
@hemish11 this has been in progress for 3 weeks. Please update progress or close if done

**Comment by hemish11** [comment]
Already being covered in https://github.com/EnsembleUI/ensemble/issues/986

**Comment by vusters** [comment]
Closed
