### ISSUE TITLE
map() an array method returns an object of array ?

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#687]
The map() method for arrays returns an object of array which is a wried behaviour for it.
Steps to reproduce 
1. Use map on any array and assign result back to some variable as here 
``` 
var dataArr = ensemble.storage.categories.map(function(value){
        return value;
    });
    console.log(dataArr);
```
here `ensemble.storage.categories` is an array.
can check it [here](https://studio.ensembleui.com/app/t0f7QDWUPIN62TIeTAY3/screen/CxFH3iAVaNl5FGtbAsmI?propertyPanelEnabled=true&instantPreviewDisabled=false&editorV2Enabled=true) as well.

Note: First run the [Home](https://studio.ensembleui.com/app/t0f7QDWUPIN62TIeTAY3/screen/9acxKxs0HdYKYZTx8xzw?propertyPanelEnabled=true&instantPreviewDisabled=false&editorV2Enabled=true) screen and then this test screen as `ensemble.storage.categories` is initialized in `Home` screen.

![image](https://github.com/EnsembleUI/ensemble/assets/62849614/0e223e75-8552-4293-b0b9-384c9e003c4f)

**Comment by kmahmood74** [comment]
checked in the fix. This should be in the next build.
