### ISSUE TITLE
Need Datagrid sorting for nested data

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#688]
Need Datagrid sorting for nested data. Currently flat data is supported but most of the time server returns nested data.

![image](https://github.com/EnsembleUI/ensemble/assets/32386713/2df46e00-1b6d-4de2-a975-027298595849)

**Comment by vusters** [comment]
@vinothvino42 consider this as the highest priority please.

**Comment by vinothvino42** [comment]
In Progress PR - #922

**Comment by vinothvino42** [comment]
@vusters Again I updated it - https://github.com/EnsembleUI/ensemble/pull/922#issuecomment-1811855515
