### ISSUE TITLE
Ability to detect if permission was granted by user to use device capabilities

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#701]
As an app developer, I want to know if user has granted access to specific device capabilities inside my Ensemble app so I can show appropriate UI.

1. push notification (immediate need)
2. location
3. storage
4. camera
5. microphone
6. contacts

**Comment by vusters** [comment]
These are mostly async, so it's ok to implement as Actions. Please also see if you can expose these to Javascript (sync)

**Comment by vinothvino42** [comment]
@vusters Do we need to check whether the permissions are enabled/disabled? OR the services are enabled/disabled by the EnsembleServices (or EnsembleModules)?

**Comment by vusters** [comment]
This is to check if the user has granted/denied permissions. So the result can be:
1. TRUE - user has granted permission
2. FALSE - user has denied
3. null - service is not enabled, or status is not available.

**Comment by vusters** [comment]
@vinothvino42 I already did #1. Please do the rest on this jira.

**Comment by vinothvino42** [comment]
Today I did it for location like how you have done it for notification but I think we need to move all the above services as a separate flutter package, right? After that can I expose a permission check method to use it from the ensemble based on that I'll set the status?

**Comment by vinothvino42** [comment]
@evshi Can you review this PR again? Added permission check support for the camera also

**Comment by vusters** [comment]
A sure way to make sure we don't inadvertently requires user permission when checking for permission is:
1. move the actual implementation to its own package (which it should be anyway)
     a. If the package is turned on, it can return true/false
     b. if the package is not turned on, the stub function can just return false.

**Comment by vinothvino42** [comment]
This issue is closed with PR #736 

It includes a permission check for the following services. 

1. Notification (Added by vu)
2. Location
3. Contacts
4. Camera

We're not using any storage or microphone direct service which requires permission. We will reopen the issue if we need anything later. Closing it as of now.
