### ISSUE TITLE
Reusable Ensemble widget

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#71]
Use Cases - 
1. As an Ensemble app developer, I want to define a custom widget in Ensemble and reuse across any view of my app.
2. Ensemble will be releasing a bunch of templates as re-usable custom widgets as well such as SummaryWidget, ProfileWidget etc.

**Comment by kmahmood74** [comment]
cc @vinothvino42

**Comment by kmahmood74** [comment]
hi @evshi kindly update the assignee to who will be working on this ticket.

**Comment by evshi** [comment]
@vinothvino42 @amin-nas @kmahmood74 here's the high level design summary https://docs.google.com/document/d/1czEpANPUtP8jSr8_XLs4E1pFzhvlvU6Ax-Ee3687898/edit

**Comment by vusters** [comment]
Fixed
