### ISSUE TITLE
Tin extension work

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#714]
1. From Swift, save a secure message to keychain. From Extension, write a placeholder function that reads the message from keychain and print it out. We give this to Tin so they can start working on their side
2. From Ensemble, we provide a javascript function `ensemble.saveToKeyChain(key, value), which will write to keychain (probably trigger the Swift code from #1 to write to keychain)
3. When our App opened with a deep link, we need to expose a onDeepLink action of some sort on Ensemble that can take the params and execute. This probably should be similar to how we listen for notifications.

If you can do #2 quickly, then skip #1.

**Comment by vinothvino42** [comment]
Here, I think the first one is not needed. Saving the token from the ensemble to the keychain using the flutter_secure_storage is fine. Then we can able to access it from App and Extension via Keychain using the app groups

**Comment by vusters** [comment]
Tin got #1 and #2 working so no additional work there. #3 is still pending.
I also added https://github.com/EnsembleUI/ensemble/issues/730 to your queue
