### ISSUE TITLE
Rendering issue with Mind Tiles

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#715]
https://discord.com/channels/1031982848485359626/1091875561447641108/1139930628322762822

**Comment by vinothvino42** [comment]
@vusters It's happening because of this - https://github.com/EnsembleUI/ensemble/blob/aacf218b09a1b122b403ddf1a08e570be87af6f2/lib/framework/view/page.dart#L287

Can I change it to white colour when the `backgroundImage` is non-null and the `backgroundColor` is null?

**Comment by vinothvino42** [comment]
It is now fixed - PR #705
