### ISSUE TITLE
Automatic back button "navigateScreen"

### ISSUE THREAD

**Issue by RuthLHanan** [EnsembleUI/ensemble#718]
When using the "navigateScreen" action, an automatic back button is generated in the header by default. However, this can be problematic when attempting to create a transparent header. It would be helpful to have a more straightforward method to disable the automatic back button in such scenarios.

**Comment by kmahmood74** [comment]
isn't there a hide back button property?

**Comment by amin-nas** [comment]
yes,

```yaml
View:
  styles:
    showNavigationIcon: false
```
