### ISSUE TITLE
Ability to disable dismissing a Dialog

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#722]
## Use Case
There's a requirement to make this screen in an app. So, my approach for this is to use dialog but it gets dismissed when tapped outside.

<img width="332" alt="Screenshot 2023-08-16 at 2 05 53 AM" src="https://github.com/EnsembleUI/ensemble/assets/32386713/773b4c4d-4817-47cb-a1ed-521eb353e60b">

## Possible Solution
- Having a boolean property like `dialogDismissEnabled` (default: true) would be nice.
- Currently, showing up a dialog can be achieved in js using `ensemble.showDialog(widgetName)`. So, this option must be available as a parameter in js code as well

**Comment by vusters** [comment]
This is purely visual. Consider styling it accordingly instead of as a modal.
