### ISSUE TITLE
AND condition not short circuiting in Js

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#724]
have some bad array (with possible null values) and im trying to filter out some data out of it while ignoring the null values using this code:

```js
var badArray = [1, 2, null, 4, 5, null, 6];
var goodArray = badArray.filter(function(e) {
  return e != null && e % 2 == 0;
})
console.log(badArray)
console.log(goodArray)
```

assuming first part of condition i.e., `e != null` should short circuit the whole condition (as AND operator is used) and not check the second part of condition, hence not throwing any error.

But it checks the second part of condition `e % 2 == 0` even first one is false! strange? 
<img width="933" alt="Screenshot 2023-08-18 at 8 40 10 AM" src="https://github.com/EnsembleUI/ensemble/assets/32386713/269b8338-d28f-41d1-b25d-d627a538fe8b">

**Comment by kmahmood74** [comment]
duplicated of #758 just fixed
