### ISSUE TITLE
Complex bindings doesn't work with js_interpreter

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#725]
Invite sent https://studio.ensembleui.com/app/fyDWXl9ykQv8Rhk20Izy/screen/MjunCLT9Og1UgimKtexC

The call to `List<String> bindings =  Bindings().resolve(JSInterpreter.parseCode(variable))` should return a list of applicable bindables so we can listen for changes to these bindables and re-evaluate the expression, but it doesn't work for some use cases:

Works (this return bindings = [name])
```
Text:
   text: ${name}
```

Doesn't work (this returns bindings = [] ):
```
Text:
  text: ${ensemble.storage.merchants[name]}
```

See the project for the actual output

**Comment by kmahmood74** [comment]
@vusters do you expect just ['name'] to be returned here or ['ensemble.storage.merchants','name']

**Comment by vusters** [comment]
both please

**Comment by kmahmood74** [comment]
fixed
