### ISSUE TITLE
Form's button aren't visible when keyboard is open

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#728]
When there is a submit button and textInputs at the bottom of the screen on clicking then keyboard opens up, and these inputs and buttons become invisible, it should squeeze the view to show these button.

See this Kitchen Sink example, here if you click on last TextInput field, it will not show you the button, also if this input was little down, this input would've also become invisible.

https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/3107baf6-dfc3-42cd-b617-61c37b31f31e

**Comment by vusters** [comment]
Fixed with https://github.com/EnsembleUI/ensemble/commit/315e17ba05167e8da789b73b4be67c46bbc01258
