### ISSUE TITLE
Page's backgroundImage shouldn't resize when keyboard is popping up

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#729]
When keyboard pops up, the screen will resize due to Scaffold's resizeToAvoidBottomInset=true. This however will resize the backgroundImage, causing some jerkiness. The fix is probably use Stack with background image as the bottom child, then put scrollable content on top.

**Comment by vusters** [comment]
Not sure if this is still an issue. Please verify @vinothvino42

**Comment by vinothvino42** [comment]
This is already fixed. See this video - https://drive.google.com/file/d/1YinwjNkcxHEc3hWAaO4XIHBrnpm9P5wf/view?usp=share_link
