### ISSUE TITLE
Action to open a hyperlink, with option to open a new tab or not

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#73]

**Comment by kmahmood74** [comment]
working on it

**Comment by kmahmood74** [comment]
checked in - support for launching urls as action. https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/TnoazbWLihcenxD1NBkr#
also supports calling, sms and email urls.
