### ISSUE TITLE
Enhance daterange control in Ensemble

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#731]
please see the attached video 

https://github.com/EnsembleUI/ensemble/assets/10066434/47eedf91-d36f-4a48-bf7b-1c3aa1047a3f

Basically we need the following for the DateRange component - 

custom widget in EDL for each date block. The actual date number is passed to this widget as an input

@vusters @evshi @vinothvino42  what do you think?

This is needed for a customer

**Comment by kmahmood74** [comment]
The design requirements have changed a bit, talk to me before starting

**Comment by kmahmood74** [comment]
@sharjeelyunus can you please share the latest design for this widget as the video I posted is out of dat

**Comment by sharjeelyunus** [comment]
There are 2 UIs for that:
   - Calendar Widget
   - DatePicker Widget
   
1. Here is the Calendar UIs, Calendar widget should be able to select the date range (startDate - endDate), On load it will show calendar on the whole screen with a bottomModal that shows seleted dates. If there is already data i.e from API we get blocked/booked dates, it should show that as well.
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/eaa49601-f5c6-49cf-9f43-ecfbd0c2beb7)

2. DatePicker Widget, we can show bottomModal with DatePicker, This date picker should be able to select the date range (startDate - endDate) and give us the selectedDate on change or save
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/b1c44cc1-c9d6-433f-8d56-ed7c00e0a75a)

**Comment by sharjeelyunus** [comment]
@vinothvino42 if you have any confusion, feel free to reach out, we can have a call, and will let you know exactly how we need it

**Comment by kmahmood74** [comment]
@vinothvino42 assigning to you. This is ready, please prioritize highly as a customer is waiting for it. Get in touch with @sharjeelyunus if you need more info.

**Comment by vinothvino42** [comment]
@kmahmood74 Okay I'll work on this issue from tomorrow

**Comment by kmahmood74** [comment]
@vusters will be taking care of it

**Comment by vusters** [comment]
@snehmehta Sending this to you. I looked at a few packages and `table_calendar` fits most of the requirements (also looked at calendar_date_picker2). The only one that may require us to extend the package is column and row spans (to overlay our own widget over several cells). I didn't get far and won't get to this for a while. Please pick this up this high priority item.

**Comment by kmahmood74** [comment]
@snehmehta @vusters I think this would be best if we provide two actions - 

selectDate
selectDateRange

This will allow dev to invoke this action from anywhere and set its properties. @sharjeelyunus already have a use case where the calendar icon appears without the input field to put the date. 

Can we please get to this right away, this is BLOCKING a customer for weeks now.
