### ISSUE TITLE
Styling OTP/Confirmation Input enhancement

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#737]
Dev should be able to configure the ConfirmationInput field as follows - 

Allow paste
Style each textfield (see attached image)

@vusters up to you, if you think it makes sense to enhance the textfield for these properties or have a separate field. 
![IMG_1249](https://github.com/EnsembleUI/ensemble/assets/10066434/76aa287d-234a-4583-bad1-b779ac6090a6)

This is needed by multiple customers.

**Comment by kmahmood74** [comment]
already works. Available as ConfirmationInput. Closing

**Comment by vusters** [comment]
Yes the paste works but i am keeping this for the styling.

**Comment by vusters** [comment]
@vinothvino42 Amin has specific requirements for additional stylings.

**Comment by kmahmood74** [comment]
Other MyPlace issues are higher priority. Kindly attend to those first like
calendar control

**Comment by vinothvino42** [comment]
> Yes the paste works but i am keeping this for the styling.
> 
> * minWidth (for the entire field)
> * fieldWidth (for individual field)

We're already having the `fieldWidth` and `fieldHeight` for each individual input field

**Comment by vusters** [comment]
@amin-nas can you provide what you need? ^

**Comment by amin-nas** [comment]
@vinothvino42 @vusters thanks for the new props. Looking good. The only outstanding issue I see is how can we make the width of the entire widget be responsive based on the device width.

![Uploading Screenshot 2023-09-26 at 10.43.53 AM.png…]()

**Comment by vinothvino42** [comment]
@amin-nas @vusters New PR - https://github.com/EnsembleUI/ensemble/pull/832
