### ISSUE TITLE
Fix notification warning when submitting app

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#741]
![Image](https://user-images.githubusercontent.com/622269/262147227-e15dad4f-32bd-486b-b9d6-fbde98d36193.png)

**Comment by vinothvino42** [comment]
In which app do I need to do this? ensemble_live (Ensemble Preview)?

**Comment by vusters** [comment]
Hey @vinothvino42 we need to move Notification to its own package, otherwise all apps will require the entitltment even when we dont' use it.

**Comment by vinothvino42** [comment]
Okay I'll do that @vusters

**Comment by vinothvino42** [comment]
Okay I'll do that @vusters 

Update: Looks like it's already assigned to sneh and there's another ticket: #740

**Comment by vusters** [comment]
Close as dup.
