### ISSUE TITLE
Move location to its own module

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#742]

**Comment by vusters** [comment]
Once moved to its own module, confirm that the following Apple warnings are no longer applicable:


![Image](https://github.com/EnsembleUI/ensemble/assets/622269/ad3eed61-f32a-4252-964a-e5ce579042be)

**Comment by kmahmood74** [comment]
this is done or still open?

**Comment by vusters** [comment]
not yet done.

**Comment by vinothvino42** [comment]
@vusters @kmahmood74 It's done now

ensemble_location Module - https://github.com/EnsembleUI/ensemble_location
ensemble Updates for the Location PR - https://github.com/EnsembleUI/ensemble/pull/1000

**Comment by kmahmood74** [comment]
resolve and merge your PR please @vinothvino42

**Comment by vinothvino42** [comment]
It's merged. Closing it
