### ISSUE TITLE
Events on user interactions with the Carousel

### ISSUE THREAD

**Issue by DonalRafferty** [EnsembleUI/ensemble#75]
There doesn't seem to be any event listeners for when a user interacts with a carousel. For example, when a user swipes between "cards" in a carousel it would be nice to have an "onChange" listener that would let us know what position in the array of content that the user is on. 

This would open up a lot of new possibilities, including changing sub content as the user swipes. However, for our use case we just need to know which item the user has switched to so we can load a detail view for that item. 

I'd imagine the listeners would follow the same structure as existing listeners for other elements such as onTap for the Button element.

**Comment by vusters** [comment]
@DonalRafferty onItemChange is added. Please review the Kitchen Sink at https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/2e1d88b1-f281-4c2c-9bb1-bd18016d2b8c.
