### ISSUE TITLE
Confirmation input need width, borderRadius and focus

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#750]
## width

For ConfirmationInput width, I want the widget to:

- take available space and divide individual inputs width accordingly
- provide width property explicitly

## borderRadius

I want to be able to set the borderRadius property

## focus

I want to be able to set focus in code

**Comment by vinothvino42** [comment]
PR - https://github.com/EnsembleUI/ensemble/pull/765
