### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#753]
I want to be able to enable pull to refresh on a screen. 

When user pulls the screens down,
- display a spinner (user should be able to customize this)

When user releases,
- trigger view's onLoad

https://github.com/EnsembleUI/ensemble/assets/491202/47ef5404-bb7e-4be2-bfa5-ed98a4bf4b90

**Comment by vusters** [comment]
@amin-nas @anserwaseem @sharjeelyunus @sibteali786 Pull to Refresh is now enabled on ListView, GridView, Column (with scrollable=true). Simply add an Action onPullToRefresh.

The pull to refresh on the root screen is a bit tougher (e.g. Tin's home screen). I'll have to spend more time on that.

**Comment by kmahmood74** [comment]
@vusters please add a kitchen sink example and documentation. This feature does not exist without it. I have been trying to use it and it doesn't work. Need example in kitchen sink please. Re-opening

**Comment by kmahmood74** [comment]
the pull to refresh is there under GridView example
