### ISSUE TITLE
Outline Button don't inherit styles like non-outline buttons

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#757]
Default styles (borderRadius, padding, ...) or theme styles are applied to Button, but Button with outline=true revert to some strange default. 
<img width="781" alt="Screenshot 2023-08-23 at 4 44 07 PM" src="https://github.com/EnsembleUI/ensemble/assets/622269/4731233f-3708-481d-9565-041f957dad5d">

**Comment by vinothvino42** [comment]
PR - #1012
