### ISSUE TITLE
BottomNavBar floating icon does not appear

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#776]
See kitchen sink example:
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/aa634599-cd5d-411c-a4b6-1163f3b5c558

![image](https://github.com/EnsembleUI/ensemble/assets/491202/31cbd836-ff67-4179-8ce5-6344a0a367bd)

**Comment by kmahmood74** [comment]
@vusters this is a huge blocker and a major regression, we have a major demo coming up. Please prioritize this!

**Comment by vinothvino42** [comment]
PR - #777
