### ISSUE TITLE
[BUG]: Date Range widget not working properly

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#779]
Not getting any data onChange using DateRange

See this Kitchen Sink Example
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/b45c5576-ec22-4b04-832f-6dd7571dd20f

**Comment by vinothvino42** [comment]
@evshi @vusters Can you review this PR - #790
