### ISSUE TITLE
TabBar styling is off

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#792]
<img width="181" alt="Screenshot 2023-09-05 at 1 53 13 PM" src="https://github.com/EnsembleUI/ensemble/assets/622269/6b4707e4-8b9f-41ac-9460-1373853b6374">

**Comment by vusters** [comment]
![Image](https://github.com/EnsembleUI/ensemble/assets/622269/366bbb13-6a75-4deb-95e7-d9af1d33656f)

**Comment by vinothvino42** [comment]
Can you share the styles of the tab bar?

**Comment by vusters** [comment]
regardless of the indicatorSize, the blue line should cover the white line no?

**Comment by vinothvino42** [comment]
Looks like it's using `indicatorSize: label`, but don't know how the white line occurs. Is that applied by you? May I know which property you used it? Can you share your styles?

**Comment by vinothvino42** [comment]
Fixed in this PR - #803
