### ISSUE TITLE
Button should have all setters just like getters

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#814]
# Use Case 
- I have a button which toggles visibility for a secion in screen
- it has two states, Show and Hide with corresponding icons.

## Issue 
- How can i set icons, the only way i get is using JS code, but it does not work 

## Error 
``` Error :  Line: 9 in YAML and Line: 7 within the code block. Error Message: Object with id:actionButtonTips does not have a gettable property named endingIcon. Code: actionButtonTips.endingIcon.name = "chevronDown"
StackTrace :  null
Line: 9 in YAML and Line: 7 within the code block. Error Message: Object with id:actionButtonTips does not have a gettable property named endingIcon. Code: actionButtonTips.endingIcon.name = "chevronDown" 
```
An example from @kmahmood74 comment on builder support issue 
The only getter for button is labelStyle - 

```  Map<String, Function> getters() {
    return {'labelStyle': () => _controller.labelStyle};
  }
```

**Comment by kmahmood74** [comment]
you don't even ned this ticket to be resolved. Your case already works. Just do this - actionButtonTips.endingIcon = "chevron_right" and it should work. No need for .name at the end. Also chevronDown is not a valid name.

**Comment by kmahmood74** [comment]
closing as not needed for now
