### ISSUE TITLE
Unable to access Ensemble-Wide Custom Widgets 

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#816]
# Use Case
- I am unable to access or use custom widgets from Ensemble Widget Library 
- it just shows any error like unsupported widget as in SS attached 

### Code Sample 
simple code like 
`ensemble.countryCodeSelector` in any screen can re-produce this issue. 
### Screen Shot
![image](https://github.com/EnsembleUI/ensemble/assets/62849614/b99d9937-c3c8-441b-9156-9738deac38a8)

**Comment by kmahmood74** [comment]
@sibteali786 is this still an issue?

**Comment by sibteali786** [comment]
@kmahmood74 no khurram, its no longer an issue.
