### ISSUE TITLE
Carousel itemTap enhancement

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#845]
In Carousel I'm showing images via item-template, now when I click an Image I want to open a new page with the full view of that image, + the new page should also be Carousel, the problem is if I click on 5th image, the newly opened page should have the Carousel with 5th image opened

Carousel
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/0bb46220-2833-49d5-b07c-179a586c81a4)

Detail image page with selected image (also a carousel)
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/1402aaa3-7a8d-46ae-8324-548f561e18de)

**Comment by vinothvino42** [comment]
PR - #846
