### ISSUE TITLE
Add action navigateViewGroup to switch to a tab

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#855]
Problem: Today the only way to switch to a ViewGroup's tab is using navigateScreen, but it will add a new ViewGroup to the view stack, even if you are already inside it.
The Ask: From within a ViewGroup's View (BottomNav, Sidebar,..), we should expose an action `navigateViewGroup` with a required param `viewIndex`.
If we are within a View within a ViewGroup, this will swich the View to tthe new index. It does nothing if not within a ViewGroup.

Look at RateAppAction to see the latest way to build an Action

**Comment by vinothvino42** [comment]
PR - https://github.com/EnsembleUI/ensemble/pull/860

**Comment by vinothvino42** [comment]
New PR - #953
