### ISSUE TITLE
Switch to monorepo

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#865]
https://github.com/EnsembleUI/ensemble/tree/monorepo
Started on it but it will not work now due to Flutter's framework limitation. The moment we reference a library in pubspec, it will include the iOS/Android dependencies, which cannot be tree-shaked. This cause all the iOS permission errors where we have to explicitly enter the permission requests even if we don't need them.

Revisit this when Flutter have a way to exclude iOS/Android code even when we import their library.

**Comment by hemish11** [comment]
Duplicate of https://github.com/EnsembleUI/ensemble/issues/1058
