### ISSUE TITLE
BottomNavBar padding and borderRadius

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#869]
for BottomNavBar I have a few customItems, like for messages, whenever you've unread messages, it shows text above the icon, that's why icons feel like attached to the bottom of the screen. That's why I need to add padding. Also, need to add borderRadius

![image](https://github.com/EnsembleUI/ensemble/assets/61178058/b9c8cf5c-8c1c-4ae0-9759-fe7adff1821f)

borderRadius like this
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/c9047eb7-ddc8-413f-9217-012d809d4eaa)

**Comment by vinothvino42** [comment]
@vusters @sharjeelyunus 
PR - https://github.com/EnsembleUI/ensemble/pull/873
