### ISSUE TITLE
Sidebar misc issues

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#870]
1) Regressions: Sidebar loads all tabs initially. It should only load the tab when that tab is selected. BottomNav seems to work properly but please check the Drawer too.
2) Sidebar/BottomNav/Drawer should have a flag `reloadView` (default true) . True means we reload the page when changing Tab, while false means we simply switch the tab without triggering refresh.

**Comment by vinothvino42** [comment]
PR - #889
