### ISSUE TITLE
Support country search

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#871]
Following https://github.com/EnsembleUI/ensemble/issues/867, please add the ability to search for a country by name, alpha-2, and alpha-3.
```
ensemble.utils.findCountry(searchText);
```
Please come up with a proposal before implementation on the Search mechanism.

**Comment by kmahmood74** [comment]
how is it going @fullstackctp ?

**Comment by fullstackctp** [comment]
> how is it going @fullstackctp ?
It is going ohk. I had a few doubts regarding the functionality that needs to be implemented. I asked sharjeel and vinoth to help me out.

**Comment by fullstackctp** [comment]
https://github.com/EnsembleUI/ensemble/assets/75938927/4db3784d-a2e7-42b0-968b-7c90dcbaec46

**Comment by kmahmood74** [comment]
fixed in #880
