### ISSUE TITLE
Array with 100 items breaks on iOS

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#881]
This screen works fine on web studio, but breaks on iOS preview app:

https://studio.ensembleui.com/app/1gx2XBQZ6HhZxsYinFKb/screen/0BKMrAfbDAe9VsILqhAI

Reducing the number of items in the array fixes the issue.

**Comment by kmahmood74** [comment]
don't think this is correct, let's close it. I am creating a new ticket for the issue I was facing
