### ISSUE TITLE
Screen shows up fine on the web but appears blank on iPhone

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#882]
This is the app, scan it - 
<img width="281" alt="image" src="https://github.com/EnsembleUI/ensemble/assets/10066434/27f9d7ba-3c4d-4acc-acf6-6aae66efa46c">

link to the screen - https://studio.ensembleui.com/app/a2qNNXgcmhBxfrTMBVGB/screen/NOLnvltgCao7UVAXuVfU

@vusters this is a blocker

**Comment by vusters** [comment]
Not sure what happened here. Confirmed that it works locally on emulator. Putting a new build up.

**Comment by kmahmood74** [comment]
yeah I ran it in simulator and it works fine on it. Also noticed that
majority of the apps on Ensemble Go do not quit when I pick "Exit App' from
the circle menu. they just stay on the same screen

**Comment by kmahmood74** [comment]
works fine now closing
