### ISSUE TITLE
openCamera additional features

### ISSUE THREAD

**Issue by RuthLHanan** [EnsembleUI/ensemble#896]
Currently there's only an option for a maxCount as type = number. I need a minCount and type = ${ensemble.storage}
Is there a way someone can make these enhancements?

**Comment by snehmehta** [comment]
Another, additional feature.
`clearExistingMedia` [here](https://discord.com/channels/1031982848485359626/1166106465480740914) is origin of it.

**Comment by snehmehta** [comment]
https://github.com/EnsembleUI/ensemble_camera/pull/4
