### ISSUE TITLE
Support adding Border to single side of Widget

### ISSUE THREAD

**Issue by Alwaz** [EnsembleUI/ensemble#898]
There should be a way to specify the side (left, right, top, bottom) on which the border should be applied.
Currently, **borderWidth** is supported and applies borders to all four sides.

**Comment by hemish11** [comment]
Here are the things im thinking about this:
- There will be `borderWidth` and `borderColor` parameters for all borderWidth thereafter we can have individual parameters like `topBorderWidth`, `topBorderColor`, and so on.
- We can also have parameters like `HorizontalBorderWidth`, `HorizontalBorderColor`, `VerticalBorderWidth`, and `VerticalBorderColor`

Also just noticed in color that we are having the same issue for BorderRadius, we can only pass borderRadius for all corners and cannot do individual. For this how about we do something like this:
- We have borderRadius as a parameter for all the corners.
- Thereafter we have parameters for individual corners like `topRightBorderRadius`.
- And also can have parameters like `topBorderRadius` for both top-left and top-right corners. Similarly for the bottom, left, and right

**Comment by kmahmood74** [comment]
suggest using the HTML/CSS standards as those are easy and well-understood. 

```
border-width: 2 #all sides have this width
border-width: 2 3 #top and bottom at 2 and right and left at 3
border-width: 2 3 4 #top at 2, right and left at 3 and bottom at 4
border-width: 2 3 4 5 #top at 2, right at 3, bottom at 4, left at 5
```
helpful link - https://www.w3schools.com/cssref/pr_border-width.php

do the same for border-radius and border-color as well. For now, this should be sufficient and we may not need to provide separate properties for border-width-left etc.

What do you think?

**Comment by hemish11** [comment]
Agreed, it would make more sense. The point 3 you mentioned seems a bit too awkward. Also according to point 3, how would I do top and bottom as 2 and left as 3 and right as 4? Else all the other case are perfect

**Comment by kmahmood74** [comment]
not sure what you mean by point 3. If you mean 

```
borderWidth: 2 3 4 #top at 2, right and left at 3 and bottom at 4
```
that's just a convenient way of assigning 3 to right and left instead of repeating it. 

Please see my comment above as I edited it.

**Comment by hemish11** [comment]
Sure, we should add both the ways like the CSS way and also the individual parameters.
For the 3rd code line, I had doubts whether is it possible if I want to have the same width for the top and bottom and different for the left and right.

**Comment by kmahmood74** [comment]
if something is not possible, just ignore it. 

Also remember to - 
1. Update the [schema](https://github.com/EnsembleUI/ensemble/blob/main/assets/schema/ensemble_schema.json). This should be part of your PR
2. document here - [docs](https://github.com/EnsembleUI/ensemble_docs) in the relevant section
