### ISSUE TITLE
Add Cookies in the Webview 

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#899]
### Use Case 
- A client needs to have authenticated access to the Webview links they provided. 
- They want us to set cookies so that they can authenticate users going through the webview from our app. 

In short if possible we should be able to set cookies from with yaml for webview so that webview is authenticated.

CC: @amin-nas @vusters @kmahmood74

**Comment by kmahmood74** [comment]
@vusters this is needed for a customer and as such is a blocker. Please prioritize. 

see this https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebViewCookieManager-class.html

It should be possible to do.

**Comment by vusters** [comment]
send this to you @fullstackctp . See EnsembleWebView.

**Comment by kmahmood74** [comment]
this was closed in https://github.com/EnsembleUI/ensemble/pull/911
