### ISSUE TITLE
clearKeychain doesn't work

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#901]
1. Running the definition below on Starter gives me error: flutter: Async Error: MissingPluginException(No implementation found for method clearKeychain on channel com.ensembleui.dev/safari-extension)
```
View:
  onLoad: |
    ensemble.clearKeychain('hi');
  body:
    Text:
      text:
```

2. Expose keychain functions (clear, saveToKeychain) as EnsembleAction

**Comment by vinothvino42** [comment]
PR - https://github.com/EnsembleUI/ensemble/pull/909
