### ISSUE TITLE
allow for a config module

### ISSUE THREAD

**Issue by muzahmed** [EnsembleUI/ensemble#929]
supply a single mode (dev/prod) per app and have the config that's supplied be responsive to that, in addition, allow overriding individual configs (as we have it today)

**Comment by kmahmood74** [comment]
we have a separate ticket for this on the studio repo, this should come this month. Ability to publish an app separately from saving it. Will allow you to have separate apps for dev/qa and prod (or as many environments as you like)

**Comment by kmahmood74** [comment]
closing as it is covered elsewhere
