### ISSUE TITLE
Carousel indicatorPosition bottomLeft required

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#952]
Right now you can only add top or bottom as indicatorPosition of carousel, but I need to use bottomLeft. Carousel should support all the positions:  

"topLeft",
"topCenter",
"topRight",
"centerLeft",
"center",
"centerRight",
"bottomLeft",
"bottomCenter",
"bottomRight"

**Comment by vinothvino42** [comment]
@kmahmood74 @sharjeelyunus It's done in this PR - #950

**Comment by vinothvino42** [comment]
@sharjeelyunus  Now you can set the topRight, bottomLeft, etc values to the `indicatorPosition` property
