### ISSUE TITLE
Need indicatorMaxCount for Carousel

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#955]
See the current version of the carousel, if a user has a lot of images it shows weird indicators messing up the styles, there should be a way to add max count of indicators. For example, if i have 10 images in Carousel and I add `indicatorMaxCount: 5` it should only show 5 indicators and allow me to scroll all 10 images  

![image](https://github.com/EnsembleUI/ensemble/assets/61178058/59092492-3eac-427d-be72-f447312ea8cc)

**Comment by vinothvino42** [comment]
PR - https://github.com/EnsembleUI/ensemble/pull/950

**Comment by kmahmood74** [comment]
@vinothvino42 this is not released yet until the PR has been merged. Not sure why you moved it to released stage. When you merge the PR, it should close this ticket automatically

**Comment by vinothvino42** [comment]
It is done - https://github.com/EnsembleUI/ensemble/pull/950
