### ISSUE TITLE
Draggable Footer

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#976]
Need a draggable footer like this

https://github.com/EnsembleUI/ensemble/assets/61178058/c86b6010-bd34-4cc8-8eb5-cba0308beb5a

**Comment by kmahmood74** [comment]
wasn't this done already? - https://github.com/EnsembleUI/ensemble/pull/910
what else is needed?
@sharjeelyunus

**Comment by snehmehta** [comment]
https://github.com/EnsembleUI/ensemble/pull/1011
