### ISSUE TITLE
BottomNavbar items with full page option

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#978]
for some pages in bottomNavbar I want to customize then open as full page (i.e remove the bottomNavbar)

**Comment by vusters** [comment]
Sending this to you @vinothvino42 .
Essentially we want to override the tap behavior on a navigation item (bottom/sidebar/drawer). Instead of loading the page, it can execute any Action.
Can we simply use the custom nav item for this?
