### ISSUE TITLE
Reusable actions

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#98]
## Background
There are use cases where I need to chain multiple actions of different types, and then trigger that set of actions on more than one event. E.g. run the action group on screen load and also when user presses a button.

## Use case
As an app developer, I want to be able to create a reusable composite action globally and call it throughout my app.

## Proposed syntax
```
# new section where I can define action groups to be reused
Actions:   

  # name the action
  myCustomAction:
    action : ...

```

**Comment by kmahmood74** [comment]
seems very low priority, closing as stale
