### ISSUE TITLE
Build APK/IPA

### ISSUE THREAD

**Issue by hemish11** [EnsembleUI/ensemble#986]
To add support for a flow that allows building APKs and IPAs by clicking one button in the Ensemble studio.

**Comment by hemish11** [comment]
Attaching proposed flow for the same:
[apk:ipa build flow.pdf](https://github.com/EnsembleUI/ensemble/files/13351502/apk.ipa.build.flow.pdf)

**Comment by hemish11** [comment]
Tasks to do for a successful build flow:
- [ ] Create a Scaffold project generation using mason
- [ ] Create a server to handle requests using Python and thereby invoke the Mason brick to generate the scaffold project
- [ ] Write code to create a new repo for a given project and push code to it. It will be done by the Python server only
- [ ] Setup CodeMagic/GitLab for the building and deployment pipeline
- [ ] Connect the CodeMagic/GitLab with the server to complete the flow
- [ ] Add a webhook for giving the live status of the build back to frontend
- [ ] Add support to restart the failed build due to some reason from the CodeMagic/GitLab platform and not recreate a scaffold project.
- [ ] Add flow in the studio. The flow would contain something like a dialog box asking for the final app name and Android and iOS package name.

**Comment by kmahmood74** [comment]
@hemish11 please update this, last update was over 4 weeks ago. Keep your tickets up-to-date, it is part of our job

**Comment by hemish11** [comment]
Both this issue and https://github.com/EnsembleUI/ensemble/issues/678 are part of the build system I'm working on, so would be closed once they are completed, let me update the checklist that's above for the new update

**Comment by kmahmood74** [comment]
closing as this has been done.
